// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type DeleteWorkspaceUserRequest struct {
	// Organization numeric identifier
	OrgID int64 `pathParam:"style=simple,explode=false,name=orgId"`
	// Workspace numeric identifier
	WorkspaceID int64 `pathParam:"style=simple,explode=false,name=workspaceId"`
	// User numeric identifier
	UserID int64 `pathParam:"style=simple,explode=false,name=userId"`
}

func (d *DeleteWorkspaceUserRequest) GetOrgID() int64 {
	if d == nil {
		return 0
	}
	return d.OrgID
}

func (d *DeleteWorkspaceUserRequest) GetWorkspaceID() int64 {
	if d == nil {
		return 0
	}
	return d.WorkspaceID
}

func (d *DeleteWorkspaceUserRequest) GetUserID() int64 {
	if d == nil {
		return 0
	}
	return d.UserID
}

type DeleteWorkspaceUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (d *DeleteWorkspaceUserResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteWorkspaceUserResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteWorkspaceUserResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteWorkspaceUserResponse) GetErrorResponse() *shared.ErrorResponse {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}
