// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type DescribeRoleRequest struct {
	// The role name
	RoleName string `pathParam:"style=simple,explode=false,name=roleName"`
	// Numeric identifier of the organization
	OrgID *int64 `queryParam:"style=form,explode=true,name=orgId"`
}

func (d *DescribeRoleRequest) GetRoleName() string {
	if d == nil {
		return ""
	}
	return d.RoleName
}

func (d *DescribeRoleRequest) GetOrgID() *int64 {
	if d == nil {
		return nil
	}
	return d.OrgID
}

type DescribeRoleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DescribeRoleResponse *shared.DescribeRoleResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (d *DescribeRoleResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DescribeRoleResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DescribeRoleResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DescribeRoleResponse) GetDescribeRoleResponse() *shared.DescribeRoleResponse {
	if d == nil {
		return nil
	}
	return d.DescribeRoleResponse
}

func (d *DescribeRoleResponse) GetErrorResponse() *shared.ErrorResponse {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}
