// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type Ga4ghRunDescribeRequest struct {
	// Run string identifier
	RunID string `pathParam:"style=simple,explode=false,name=run_id"`
}

func (g *Ga4ghRunDescribeRequest) GetRunID() string {
	if g == nil {
		return ""
	}
	return g.RunID
}

// #region class-body-ga4ghrundescriberequest
// #endregion class-body-ga4ghrundescriberequest

type Ga4ghRunDescribeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	RunLog *shared.RunLog
	// Bad request
	WesErrorResponse *shared.WesErrorResponse
}

func (g *Ga4ghRunDescribeResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *Ga4ghRunDescribeResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *Ga4ghRunDescribeResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *Ga4ghRunDescribeResponse) GetRunLog() *shared.RunLog {
	if g == nil {
		return nil
	}
	return g.RunLog
}

func (g *Ga4ghRunDescribeResponse) GetWesErrorResponse() *shared.WesErrorResponse {
	if g == nil {
		return nil
	}
	return g.WesErrorResponse
}

// #region class-body-ga4ghrundescriberesponse
// #endregion class-body-ga4ghrundescriberesponse
