// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type GenerateDownloadURLDataLinkRequest struct {
	// Data-link string identifier
	DataLinkID string `pathParam:"style=simple,explode=false,name=dataLinkId"`
	// File path to download
	FilePath *string `queryParam:"style=form,explode=true,name=filePath"`
	// Credentials string identifier
	CredentialsID *string `queryParam:"style=form,explode=true,name=credentialsId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Whether to generate the URL for preview purposes or direct download (default: false)
	Preview *bool `queryParam:"style=form,explode=true,name=preview"`
	// When true, treats the file as a Fusion symlink and resolves its target (default: false)
	ResolveSymlink *bool `queryParam:"style=form,explode=true,name=resolveSymlink"`
}

func (g *GenerateDownloadURLDataLinkRequest) GetDataLinkID() string {
	if g == nil {
		return ""
	}
	return g.DataLinkID
}

func (g *GenerateDownloadURLDataLinkRequest) GetFilePath() *string {
	if g == nil {
		return nil
	}
	return g.FilePath
}

func (g *GenerateDownloadURLDataLinkRequest) GetCredentialsID() *string {
	if g == nil {
		return nil
	}
	return g.CredentialsID
}

func (g *GenerateDownloadURLDataLinkRequest) GetWorkspaceID() *int64 {
	if g == nil {
		return nil
	}
	return g.WorkspaceID
}

func (g *GenerateDownloadURLDataLinkRequest) GetPreview() *bool {
	if g == nil {
		return nil
	}
	return g.Preview
}

func (g *GenerateDownloadURLDataLinkRequest) GetResolveSymlink() *bool {
	if g == nil {
		return nil
	}
	return g.ResolveSymlink
}

type GenerateDownloadURLDataLinkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DataLinkDownloadURLResponse *shared.DataLinkDownloadURLResponse
	// BadRequest
	ErrorResponse *shared.ErrorResponse
}

func (g *GenerateDownloadURLDataLinkResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GenerateDownloadURLDataLinkResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GenerateDownloadURLDataLinkResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GenerateDownloadURLDataLinkResponse) GetDataLinkDownloadURLResponse() *shared.DataLinkDownloadURLResponse {
	if g == nil {
		return nil
	}
	return g.DataLinkDownloadURLResponse
}

func (g *GenerateDownloadURLDataLinkResponse) GetErrorResponse() *shared.ErrorResponse {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}
