// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type GetEncryptedCredentialsRequest struct {
	// Credentials string identifier
	CredentialsID string `pathParam:"style=simple,explode=false,name=credentialsId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Encryption key string identifier
	PairingID *string `queryParam:"style=form,explode=true,name=pairingId"`
}

func (g *GetEncryptedCredentialsRequest) GetCredentialsID() string {
	if g == nil {
		return ""
	}
	return g.CredentialsID
}

func (g *GetEncryptedCredentialsRequest) GetWorkspaceID() *int64 {
	if g == nil {
		return nil
	}
	return g.WorkspaceID
}

func (g *GetEncryptedCredentialsRequest) GetPairingID() *string {
	if g == nil {
		return nil
	}
	return g.PairingID
}

type GetEncryptedCredentialsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	GetCredentialsKeysResponse *shared.GetCredentialsKeysResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (g *GetEncryptedCredentialsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetEncryptedCredentialsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetEncryptedCredentialsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetEncryptedCredentialsResponse) GetGetCredentialsKeysResponse() *shared.GetCredentialsKeysResponse {
	if g == nil {
		return nil
	}
	return g.GetCredentialsKeysResponse
}

func (g *GetEncryptedCredentialsResponse) GetErrorResponse() *shared.ErrorResponse {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}
