// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type UpdatePipelineVersionRequest struct {
	// Pipeline numeric identifier
	PipelineID int64 `pathParam:"style=simple,explode=false,name=pipelineId"`
	// Pipeline version string identifier
	VersionID string `pathParam:"style=simple,explode=false,name=versionId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Pipeline version update request
	UpdatePipelineRequest shared.UpdatePipelineRequest `request:"mediaType=application/json"`
}

func (u *UpdatePipelineVersionRequest) GetPipelineID() int64 {
	if u == nil {
		return 0
	}
	return u.PipelineID
}

func (u *UpdatePipelineVersionRequest) GetVersionID() string {
	if u == nil {
		return ""
	}
	return u.VersionID
}

func (u *UpdatePipelineVersionRequest) GetWorkspaceID() *int64 {
	if u == nil {
		return nil
	}
	return u.WorkspaceID
}

func (u *UpdatePipelineVersionRequest) GetUpdatePipelineRequest() shared.UpdatePipelineRequest {
	if u == nil {
		return shared.UpdatePipelineRequest{}
	}
	return u.UpdatePipelineRequest
}

type UpdatePipelineVersionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	UpdatePipelineResponse *shared.UpdatePipelineResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (u *UpdatePipelineVersionResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdatePipelineVersionResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdatePipelineVersionResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdatePipelineVersionResponse) GetUpdatePipelineResponse() *shared.UpdatePipelineResponse {
	if u == nil {
		return nil
	}
	return u.UpdatePipelineResponse
}

func (u *UpdatePipelineVersionResponse) GetErrorResponse() *shared.ErrorResponse {
	if u == nil {
		return nil
	}
	return u.ErrorResponse
}
