// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type AwsCredentialsMode string

const (
	AwsCredentialsModeKeys AwsCredentialsMode = "keys"
	AwsCredentialsModeRole AwsCredentialsMode = "role"
)

func (e AwsCredentialsMode) ToPointer() *AwsCredentialsMode {
	return &e
}
func (e *AwsCredentialsMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "keys":
		fallthrough
	case "role":
		*e = AwsCredentialsMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AwsCredentialsMode: %v", v)
	}
}
