// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
)

type AzBatchPlatformMetainfo struct {
	Containers []string `json:"containers,omitempty"`
	// property to select the platform metainfo type
	Discriminator *string  `json:"discriminator,omitempty"`
	Pools         []string `json:"pools,omitempty"`
	VMTypes       []string `json:"vmTypes,omitempty"`
	Warnings      []string `json:"warnings,omitempty"`
}

func (a AzBatchPlatformMetainfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzBatchPlatformMetainfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzBatchPlatformMetainfo) GetContainers() []string {
	if a == nil {
		return nil
	}
	return a.Containers
}

func (a *AzBatchPlatformMetainfo) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AzBatchPlatformMetainfo) GetPools() []string {
	if a == nil {
		return nil
	}
	return a.Pools
}

func (a *AzBatchPlatformMetainfo) GetVMTypes() []string {
	if a == nil {
		return nil
	}
	return a.VMTypes
}

func (a *AzBatchPlatformMetainfo) GetWarnings() []string {
	if a == nil {
		return nil
	}
	return a.Warnings
}
