// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
)

type BucketActionConfig struct {
	BucketName      *string  `json:"bucketName,omitempty"`
	DataLinkID      *string  `json:"dataLinkId,omitempty"`
	DatasetID       *string  `json:"datasetId,omitempty"`
	Discriminator   *string  `json:"discriminator,omitempty"`
	Events          []string `json:"events,omitempty"`
	Filter          *string  `json:"filter,omitempty"`
	MarkerFile      *string  `json:"markerFile,omitempty"`
	SubscriptionArn *string  `json:"subscriptionArn,omitempty"`
	TopicArn        *string  `json:"topicArn,omitempty"`
}

func (b BucketActionConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BucketActionConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BucketActionConfig) GetBucketName() *string {
	if b == nil {
		return nil
	}
	return b.BucketName
}

func (b *BucketActionConfig) GetDataLinkID() *string {
	if b == nil {
		return nil
	}
	return b.DataLinkID
}

func (b *BucketActionConfig) GetDatasetID() *string {
	if b == nil {
		return nil
	}
	return b.DatasetID
}

func (b *BucketActionConfig) GetDiscriminator() *string {
	if b == nil {
		return nil
	}
	return b.Discriminator
}

func (b *BucketActionConfig) GetEvents() []string {
	if b == nil {
		return nil
	}
	return b.Events
}

func (b *BucketActionConfig) GetFilter() *string {
	if b == nil {
		return nil
	}
	return b.Filter
}

func (b *BucketActionConfig) GetMarkerFile() *string {
	if b == nil {
		return nil
	}
	return b.MarkerFile
}

func (b *BucketActionConfig) GetSubscriptionArn() *string {
	if b == nil {
		return nil
	}
	return b.SubscriptionArn
}

func (b *BucketActionConfig) GetTopicArn() *string {
	if b == nil {
		return nil
	}
	return b.TopicArn
}
