// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BucketActionRequest struct {
	DataLinkID *string  `json:"dataLinkId,omitempty"`
	DatasetID  *string  `json:"datasetId,omitempty"`
	Events     []string `json:"events,omitempty"`
	Filter     *string  `json:"filter,omitempty"`
	MarkerFile *string  `json:"markerFile,omitempty"`
}

func (b *BucketActionRequest) GetDataLinkID() *string {
	if b == nil {
		return nil
	}
	return b.DataLinkID
}

func (b *BucketActionRequest) GetDatasetID() *string {
	if b == nil {
		return nil
	}
	return b.DatasetID
}

func (b *BucketActionRequest) GetEvents() []string {
	if b == nil {
		return nil
	}
	return b.Events
}

func (b *BucketActionRequest) GetFilter() *string {
	if b == nil {
		return nil
	}
	return b.Filter
}

func (b *BucketActionRequest) GetMarkerFile() *string {
	if b == nil {
		return nil
	}
	return b.MarkerFile
}
