// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

type ComputeEnvResponseDtoPlatform string

const (
	ComputeEnvResponseDtoPlatformAwsBatch              ComputeEnvResponseDtoPlatform = "aws-batch"
	ComputeEnvResponseDtoPlatformAwsCloud              ComputeEnvResponseDtoPlatform = "aws-cloud"
	ComputeEnvResponseDtoPlatformSeqeracomputePlatform ComputeEnvResponseDtoPlatform = "seqeracompute-platform"
	ComputeEnvResponseDtoPlatformGoogleBatch           ComputeEnvResponseDtoPlatform = "google-batch"
	ComputeEnvResponseDtoPlatformGoogleCloud           ComputeEnvResponseDtoPlatform = "google-cloud"
	ComputeEnvResponseDtoPlatformAzureBatch            ComputeEnvResponseDtoPlatform = "azure-batch"
	ComputeEnvResponseDtoPlatformAzureCloud            ComputeEnvResponseDtoPlatform = "azure-cloud"
	ComputeEnvResponseDtoPlatformK8sPlatform           ComputeEnvResponseDtoPlatform = "k8s-platform"
	ComputeEnvResponseDtoPlatformEksPlatform           ComputeEnvResponseDtoPlatform = "eks-platform"
	ComputeEnvResponseDtoPlatformGkePlatform           ComputeEnvResponseDtoPlatform = "gke-platform"
	ComputeEnvResponseDtoPlatformUgePlatform           ComputeEnvResponseDtoPlatform = "uge-platform"
	ComputeEnvResponseDtoPlatformSlurmPlatform         ComputeEnvResponseDtoPlatform = "slurm-platform"
	ComputeEnvResponseDtoPlatformLsfPlatform           ComputeEnvResponseDtoPlatform = "lsf-platform"
	ComputeEnvResponseDtoPlatformAltairPlatform        ComputeEnvResponseDtoPlatform = "altair-platform"
	ComputeEnvResponseDtoPlatformMoabPlatform          ComputeEnvResponseDtoPlatform = "moab-platform"
	ComputeEnvResponseDtoPlatformLocalPlatform         ComputeEnvResponseDtoPlatform = "local-platform"
	ComputeEnvResponseDtoPlatformGoogleLifesciences    ComputeEnvResponseDtoPlatform = "google-lifesciences"
)

func (e ComputeEnvResponseDtoPlatform) ToPointer() *ComputeEnvResponseDtoPlatform {
	return &e
}
func (e *ComputeEnvResponseDtoPlatform) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "aws-batch":
		fallthrough
	case "aws-cloud":
		fallthrough
	case "seqeracompute-platform":
		fallthrough
	case "google-batch":
		fallthrough
	case "google-cloud":
		fallthrough
	case "azure-batch":
		fallthrough
	case "azure-cloud":
		fallthrough
	case "k8s-platform":
		fallthrough
	case "eks-platform":
		fallthrough
	case "gke-platform":
		fallthrough
	case "uge-platform":
		fallthrough
	case "slurm-platform":
		fallthrough
	case "lsf-platform":
		fallthrough
	case "altair-platform":
		fallthrough
	case "moab-platform":
		fallthrough
	case "local-platform":
		fallthrough
	case "google-lifesciences":
		*e = ComputeEnvResponseDtoPlatform(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ComputeEnvResponseDtoPlatform: %v", v)
	}
}

type ComputeEnvResponseDtoResources struct {
	Cpus           *int     `json:"cpus,omitempty"`
	DiskSize       *int     `json:"diskSize,omitempty"`
	EstimatedPrice *float32 `json:"estimatedPrice,omitempty"`
	Gpus           *int     `json:"gpus,omitempty"`
	InstanceType   *string  `json:"instanceType,omitempty"`
	Memory         *int     `json:"memory,omitempty"`
}

func (c *ComputeEnvResponseDtoResources) GetCpus() *int {
	if c == nil {
		return nil
	}
	return c.Cpus
}

func (c *ComputeEnvResponseDtoResources) GetDiskSize() *int {
	if c == nil {
		return nil
	}
	return c.DiskSize
}

func (c *ComputeEnvResponseDtoResources) GetEstimatedPrice() *float32 {
	if c == nil {
		return nil
	}
	return c.EstimatedPrice
}

func (c *ComputeEnvResponseDtoResources) GetGpus() *int {
	if c == nil {
		return nil
	}
	return c.Gpus
}

func (c *ComputeEnvResponseDtoResources) GetInstanceType() *string {
	if c == nil {
		return nil
	}
	return c.InstanceType
}

func (c *ComputeEnvResponseDtoResources) GetMemory() *int {
	if c == nil {
		return nil
	}
	return c.Memory
}

type ComputeEnvResponseDto struct {
	AwsAccountID *string `json:"awsAccountId,omitempty"`
	// Configuration settings for compute environments including work directories,
	// pre/post run scripts, and environment-specific parameters.
	//
	Config *ComputeConfig `json:"config,omitempty"`
	// Associated credentials ID (null if using managed identity or none)
	CredentialsID *string    `json:"credentialsId,omitempty"`
	DateCreated   *time.Time `json:"dateCreated,omitempty"`
	// Whether compute environment is deleted (null means not deleted)
	Deleted *bool `json:"deleted,omitempty"`
	// Compute environment description
	Description  *string      `json:"description,omitempty"`
	ComputeEnvID *string      `json:"id,omitempty"`
	Labels       []LabelDbDto `json:"labels,omitempty"`
	LastUpdated  *time.Time   `json:"lastUpdated,omitempty"`
	// Last time this compute environment was used (null if never used)
	LastUsed *time.Time `json:"lastUsed,omitempty"`
	// Associated managed identity ID (null if using credentials or none)
	ManagedIdentityID *string `json:"managedIdentityId,omitempty"`
	// Status message (null if no message)
	Message  *string                        `json:"message,omitempty"`
	Name     *string                        `json:"name,omitempty"`
	OrgID    *int64                         `json:"orgId,omitempty"`
	Platform *ComputeEnvResponseDtoPlatform `json:"platform,omitempty"`
	// Whether this is the primary compute environment
	Primary     *bool                           `json:"primary,omitempty"`
	Resources   *ComputeEnvResponseDtoResources `json:"resources,omitempty"`
	Status      *ComputeEnvStatus               `json:"status,omitempty"`
	WorkspaceID *int64                          `json:"workspaceId,omitempty"`
}

func (c ComputeEnvResponseDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ComputeEnvResponseDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetAwsAccountID() *string {
	if c == nil {
		return nil
	}
	return c.AwsAccountID
}

func (c *ComputeEnvResponseDto) GetConfig() *ComputeConfig {
	if c == nil {
		return nil
	}
	return c.Config
}

func (c *ComputeEnvResponseDto) GetConfigMoabPlatform() *MoabConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.MoabConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigAwsBatch() *AWSBatchConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.AWSBatchConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigGoogleCloud() *GoogleCloudConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.GoogleCloudConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigLocalPlatform() *LocalExecutionConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.LocalExecutionConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigAzureCloud() *AzureCloudConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.AzureCloudConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigGkePlatform() *GoogleGKEClusterConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.GoogleGKEClusterConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigGoogleBatch() *GoogleBatchServiceConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.GoogleBatchServiceConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigAwsCloud() *AWSCloudConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.AWSCloudConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigSlurmPlatform() *SlurmConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.SlurmConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigK8sPlatform() *KubernetesComputeConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.KubernetesComputeConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigAltairPlatform() *AltairPBSConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.AltairPBSConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigLsfPlatform() *IBMLSFConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.IBMLSFConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigAzureBatch() *AzureBatchConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.AzureBatchConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigSeqeracomputePlatform() *SeqeraComputeConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.SeqeraComputeConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigEksPlatform() *AmazonEKSClusterConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.AmazonEKSClusterConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigUgePlatform() *UnivaGridEngineConfiguration {
	if v := c.GetConfig(); v != nil {
		return v.UnivaGridEngineConfiguration
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetConfigGoogleLifesciences() *GoogleLifeSciencesConfigurationRetired {
	if v := c.GetConfig(); v != nil {
		return v.GoogleLifeSciencesConfigurationRetired
	}
	return nil
}

func (c *ComputeEnvResponseDto) GetCredentialsID() *string {
	if c == nil {
		return nil
	}
	return c.CredentialsID
}

func (c *ComputeEnvResponseDto) GetDateCreated() *time.Time {
	if c == nil {
		return nil
	}
	return c.DateCreated
}

func (c *ComputeEnvResponseDto) GetDeleted() *bool {
	if c == nil {
		return nil
	}
	return c.Deleted
}

func (c *ComputeEnvResponseDto) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *ComputeEnvResponseDto) GetComputeEnvID() *string {
	if c == nil {
		return nil
	}
	return c.ComputeEnvID
}

func (c *ComputeEnvResponseDto) GetLabels() []LabelDbDto {
	if c == nil {
		return nil
	}
	return c.Labels
}

func (c *ComputeEnvResponseDto) GetLastUpdated() *time.Time {
	if c == nil {
		return nil
	}
	return c.LastUpdated
}

func (c *ComputeEnvResponseDto) GetLastUsed() *time.Time {
	if c == nil {
		return nil
	}
	return c.LastUsed
}

func (c *ComputeEnvResponseDto) GetManagedIdentityID() *string {
	if c == nil {
		return nil
	}
	return c.ManagedIdentityID
}

func (c *ComputeEnvResponseDto) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *ComputeEnvResponseDto) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *ComputeEnvResponseDto) GetOrgID() *int64 {
	if c == nil {
		return nil
	}
	return c.OrgID
}

func (c *ComputeEnvResponseDto) GetPlatform() *ComputeEnvResponseDtoPlatform {
	if c == nil {
		return nil
	}
	return c.Platform
}

func (c *ComputeEnvResponseDto) GetPrimary() *bool {
	if c == nil {
		return nil
	}
	return c.Primary
}

func (c *ComputeEnvResponseDto) GetResources() *ComputeEnvResponseDtoResources {
	if c == nil {
		return nil
	}
	return c.Resources
}

func (c *ComputeEnvResponseDto) GetStatus() *ComputeEnvStatus {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *ComputeEnvResponseDto) GetWorkspaceID() *int64 {
	if c == nil {
		return nil
	}
	return c.WorkspaceID
}
