// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateRoleRequest struct {
	Description string   `json:"description"`
	Name        *string  `json:"name,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
}

func (c *CreateRoleRequest) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *CreateRoleRequest) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateRoleRequest) GetPermissions() []string {
	if c == nil {
		return nil
	}
	return c.Permissions
}
