// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateLabelResponse struct {
	LabelID   *int64  `json:"id,omitempty"`
	IsDefault *bool   `json:"isDefault,omitempty"`
	Name      *string `json:"name,omitempty"`
	Resource  *bool   `json:"resource,omitempty"`
	Value     *string `json:"value,omitempty"`
}

func (c *CreateLabelResponse) GetLabelID() *int64 {
	if c == nil {
		return nil
	}
	return c.LabelID
}

func (c *CreateLabelResponse) GetIsDefault() *bool {
	if c == nil {
		return nil
	}
	return c.IsDefault
}

func (c *CreateLabelResponse) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateLabelResponse) GetResource() *bool {
	if c == nil {
		return nil
	}
	return c.Resource
}

func (c *CreateLabelResponse) GetValue() *string {
	if c == nil {
		return nil
	}
	return c.Value
}
