// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

type DataStudioCheckpointDto struct {
	Author      *UserInfo `json:"author"`
	DateCreated time.Time `json:"dateCreated"`
	// Date checkpoint was saved (null if not saved)
	DateSaved *time.Time              `json:"dateSaved"`
	ID        int64                   `json:"id"`
	Name      string                  `json:"name"`
	Path      string                  `json:"path"`
	Status    *StudioCheckpointStatus `json:"status"`
}

func (d DataStudioCheckpointDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DataStudioCheckpointDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DataStudioCheckpointDto) GetAuthor() *UserInfo {
	if d == nil {
		return nil
	}
	return d.Author
}

func (d *DataStudioCheckpointDto) GetDateCreated() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.DateCreated
}

func (d *DataStudioCheckpointDto) GetDateSaved() *time.Time {
	if d == nil {
		return nil
	}
	return d.DateSaved
}

func (d *DataStudioCheckpointDto) GetID() int64 {
	if d == nil {
		return 0
	}
	return d.ID
}

func (d *DataStudioCheckpointDto) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DataStudioCheckpointDto) GetPath() string {
	if d == nil {
		return ""
	}
	return d.Path
}

func (d *DataStudioCheckpointDto) GetStatus() *StudioCheckpointStatus {
	if d == nil {
		return nil
	}
	return d.Status
}
