// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DataStudioWorkspaceSettingsResponse struct {
	ContainerRepository    *string `json:"containerRepository,omitempty"`
	LifespanHours          *int    `json:"lifespanHours,omitempty"`
	OrgID                  *int64  `json:"orgId,omitempty"`
	PrivateStudioByDefault *bool   `json:"privateStudioByDefault,omitempty"`
	WspID                  *int64  `json:"wspId,omitempty"`
}

func (d *DataStudioWorkspaceSettingsResponse) GetContainerRepository() *string {
	if d == nil {
		return nil
	}
	return d.ContainerRepository
}

func (d *DataStudioWorkspaceSettingsResponse) GetLifespanHours() *int {
	if d == nil {
		return nil
	}
	return d.LifespanHours
}

func (d *DataStudioWorkspaceSettingsResponse) GetOrgID() *int64 {
	if d == nil {
		return nil
	}
	return d.OrgID
}

func (d *DataStudioWorkspaceSettingsResponse) GetPrivateStudioByDefault() *bool {
	if d == nil {
		return nil
	}
	return d.PrivateStudioByDefault
}

func (d *DataStudioWorkspaceSettingsResponse) GetWspID() *int64 {
	if d == nil {
		return nil
	}
	return d.WspID
}
