// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

// DatasetDto - Represents a dataset in the Seqera Platform.
// Contains dataset metadata, versioning information, and access
// controls for data management and sharing.
type DatasetDto struct {
	// Detailed description of the dataset contents and purpose (max 1000 characters)
	Description *string `json:"description,omitempty"`
	// Unique identifier for the dataset (max 22 characters)
	ID *string `json:"id,omitempty"`
	// Timestamp when the dataset was last modified
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	// MIME type or media type of the dataset content (max 80 characters)
	MediaType *string `json:"mediaType,omitempty"`
	// Dataset name following naming conventions (1-100 characters)
	Name *string `json:"name,omitempty"`
	// Numeric identifier of the workspace containing this dataset
	WorkspaceID *int64 `json:"workspaceId,omitempty"`
}

func (d DatasetDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DatasetDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DatasetDto) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *DatasetDto) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DatasetDto) GetLastUpdated() *time.Time {
	if d == nil {
		return nil
	}
	return d.LastUpdated
}

func (d *DatasetDto) GetMediaType() *string {
	if d == nil {
		return nil
	}
	return d.MediaType
}

func (d *DatasetDto) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *DatasetDto) GetWorkspaceID() *int64 {
	if d == nil {
		return nil
	}
	return d.WorkspaceID
}
