// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DataStudioWorkspaceSettingsRequest struct {
	LifespanHours          *int    `json:"lifespanHours,omitempty"`
	ContainerRepository    *string `json:"containerRepository,omitempty"`
	PrivateStudioByDefault *bool   `json:"privateStudioByDefault,omitempty"`
}

func (d *DataStudioWorkspaceSettingsRequest) GetLifespanHours() *int {
	if d == nil {
		return nil
	}
	return d.LifespanHours
}

func (d *DataStudioWorkspaceSettingsRequest) GetContainerRepository() *string {
	if d == nil {
		return nil
	}
	return d.ContainerRepository
}

func (d *DataStudioWorkspaceSettingsRequest) GetPrivateStudioByDefault() *bool {
	if d == nil {
		return nil
	}
	return d.PrivateStudioByDefault
}
