// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DataLinkUpdateRequest struct {
	CredentialsID *string `json:"credentialsId,omitempty"`
	Description   *string `json:"description,omitempty"`
	Name          *string `json:"name,omitempty"`
}

func (d *DataLinkUpdateRequest) GetCredentialsID() *string {
	if d == nil {
		return nil
	}
	return d.CredentialsID
}

func (d *DataLinkUpdateRequest) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *DataLinkUpdateRequest) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}
