// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DeleteDatasetsResponse struct {
	Failed  []string `json:"failed,omitempty"`
	Success []string `json:"success,omitempty"`
}

func (d *DeleteDatasetsResponse) GetFailed() []string {
	if d == nil {
		return nil
	}
	return d.Failed
}

func (d *DeleteDatasetsResponse) GetSuccess() []string {
	if d == nil {
		return nil
	}
	return d.Success
}
