// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DescribeWorkflowResponse struct {
	PipelineInfo *PipelineMinInfoResponse `json:"pipelineInfo,omitempty"`
	Workflow     *WorkflowMaxDbDto        `json:"workflow,omitempty"`
	WorkspaceID  *int64                   `json:"workspaceId,omitempty"`
}

func (d *DescribeWorkflowResponse) GetPipelineInfo() *PipelineMinInfoResponse {
	if d == nil {
		return nil
	}
	return d.PipelineInfo
}

func (d *DescribeWorkflowResponse) GetWorkflow() *WorkflowMaxDbDto {
	if d == nil {
		return nil
	}
	return d.Workflow
}

func (d *DescribeWorkflowResponse) GetWorkspaceID() *int64 {
	if d == nil {
		return nil
	}
	return d.WorkspaceID
}
