// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListRolePermissionsResponse struct {
	Permissions []RolePermissionResponseDto `json:"permissions,omitempty"`
}

func (l *ListRolePermissionsResponse) GetPermissions() []RolePermissionResponseDto {
	if l == nil {
		return nil
	}
	return l.Permissions
}
