// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListSSHKeysResponse struct {
	SSHKeys []UserSSHPublicKeyDto `json:"sshKeys,omitempty"`
}

func (l *ListSSHKeysResponse) GetSSHKeys() []UserSSHPublicKeyDto {
	if l == nil {
		return nil
	}
	return l.SSHKeys
}
