// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type MountData struct {
	DataLinkID *string `json:"dataLinkId,omitempty"`
	Path       *string `json:"path,omitempty"`
}

func (m *MountData) GetDataLinkID() *string {
	if m == nil {
		return nil
	}
	return m.DataLinkID
}

func (m *MountData) GetPath() *string {
	if m == nil {
		return nil
	}
	return m.Path
}
