// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// MemberRole - Member role (can be null for collaborators)
type MemberRole string

const (
	MemberRoleOwner        MemberRole = "owner"
	MemberRoleMember       MemberRole = "member"
	MemberRoleCollaborator MemberRole = "collaborator"
)

func (e MemberRole) ToPointer() *MemberRole {
	return &e
}
func (e *MemberRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "owner":
		fallthrough
	case "member":
		fallthrough
	case "collaborator":
		*e = MemberRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MemberRole: %v", v)
	}
}

// OrganizationDbDto - Represents an organization in the Seqera Platform.
// Contains organizational metadata, settings, and member management
// information for multi-tenant environments.
type OrganizationDbDto struct {
	// Detailed description of the organization's purpose and activities
	Description *string `json:"description,omitempty"`
	// Complete formal display name of the organization
	FullName *string `json:"fullName,omitempty"`
	// Geographic location or address of the organization
	Location *string `json:"location,omitempty"`
	// Member ID (can be null for collaborators)
	MemberID *int64 `json:"memberId,omitempty"`
	// Member role (can be null for collaborators)
	MemberRole *MemberRole `json:"memberRole,omitempty"`
	// Short name or handle for the organization (used in URLs and paths)
	Name *string `json:"name,omitempty"`
	// Unique numeric identifier for the organization
	OrgID *int64 `json:"orgId,omitempty"`
	// Official website URL for the organization
	Website *string `json:"website,omitempty"`
}

func (o *OrganizationDbDto) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OrganizationDbDto) GetFullName() *string {
	if o == nil {
		return nil
	}
	return o.FullName
}

func (o *OrganizationDbDto) GetLocation() *string {
	if o == nil {
		return nil
	}
	return o.Location
}

func (o *OrganizationDbDto) GetMemberID() *int64 {
	if o == nil {
		return nil
	}
	return o.MemberID
}

func (o *OrganizationDbDto) GetMemberRole() *MemberRole {
	if o == nil {
		return nil
	}
	return o.MemberRole
}

func (o *OrganizationDbDto) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *OrganizationDbDto) GetOrgID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *OrganizationDbDto) GetWebsite() *string {
	if o == nil {
		return nil
	}
	return o.Website
}
