// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type OrgAndWorkspaceDto struct {
	OrgID             *int64      `json:"orgId,omitempty"`
	OrgLogoURL        *string     `json:"orgLogoUrl,omitempty"`
	OrgName           *string     `json:"orgName,omitempty"`
	OrgType           *OrgType    `json:"orgType,omitempty"`
	Roles             []string    `json:"roles,omitempty"`
	Visibility        *Visibility `json:"visibility,omitempty"`
	WorkspaceFullName *string     `json:"workspaceFullName,omitempty"`
	WorkspaceID       *int64      `json:"workspaceId,omitempty"`
	WorkspaceName     *string     `json:"workspaceName,omitempty"`
}

func (o *OrgAndWorkspaceDto) GetOrgID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *OrgAndWorkspaceDto) GetOrgLogoURL() *string {
	if o == nil {
		return nil
	}
	return o.OrgLogoURL
}

func (o *OrgAndWorkspaceDto) GetOrgName() *string {
	if o == nil {
		return nil
	}
	return o.OrgName
}

func (o *OrgAndWorkspaceDto) GetOrgType() *OrgType {
	if o == nil {
		return nil
	}
	return o.OrgType
}

func (o *OrgAndWorkspaceDto) GetRoles() []string {
	if o == nil {
		return nil
	}
	return o.Roles
}

func (o *OrgAndWorkspaceDto) GetVisibility() *Visibility {
	if o == nil {
		return nil
	}
	return o.Visibility
}

func (o *OrgAndWorkspaceDto) GetWorkspaceFullName() *string {
	if o == nil {
		return nil
	}
	return o.WorkspaceFullName
}

func (o *OrgAndWorkspaceDto) GetWorkspaceID() *int64 {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

func (o *OrgAndWorkspaceDto) GetWorkspaceName() *string {
	if o == nil {
		return nil
	}
	return o.WorkspaceName
}
