// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PipelineSchemaDbDto struct {
	ID      *int64  `json:"id,omitempty"`
	Content *string `json:"content,omitempty"`
}

func (p *PipelineSchemaDbDto) GetID() *int64 {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PipelineSchemaDbDto) GetContent() *string {
	if p == nil {
		return nil
	}
	return p.Content
}
