// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ProgressData struct {
	ProcessesProgress []ProcessLoad `json:"processesProgress,omitempty"`
	TotalProcesses    *int          `json:"totalProcesses,omitempty"`
	WorkflowProgress  *WorkflowLoad `json:"workflowProgress,omitempty"`
}

func (p *ProgressData) GetProcessesProgress() []ProcessLoad {
	if p == nil {
		return nil
	}
	return p.ProcessesProgress
}

func (p *ProgressData) GetTotalProcesses() *int {
	if p == nil {
		return nil
	}
	return p.TotalProcesses
}

func (p *ProgressData) GetWorkflowProgress() *WorkflowLoad {
	if p == nil {
		return nil
	}
	return p.WorkflowProgress
}
