// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
)

type LocalSecurityKeys struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Password      *string `json:"password,omitempty"`
}

func (l LocalSecurityKeys) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LocalSecurityKeys) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LocalSecurityKeys) GetDiscriminator() *string {
	if l == nil {
		return nil
	}
	return l.Discriminator
}

func (l *LocalSecurityKeys) GetPassword() *string {
	if l == nil {
		return nil
	}
	return l.Password
}

type S3CompatibleCredentials struct {
	Discriminator          *string `json:"discriminator,omitempty"`
	AccessKey              *string `json:"accessKey,omitempty"`
	SecretKey              *string `json:"secretKey,omitempty"`
	PathStyleAccessEnabled *bool   `json:"pathStyleAccessEnabled,omitempty"`
}

func (s S3CompatibleCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *S3CompatibleCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *S3CompatibleCredentials) GetDiscriminator() *string {
	if s == nil {
		return nil
	}
	return s.Discriminator
}

func (s *S3CompatibleCredentials) GetAccessKey() *string {
	if s == nil {
		return nil
	}
	return s.AccessKey
}

func (s *S3CompatibleCredentials) GetSecretKey() *string {
	if s == nil {
		return nil
	}
	return s.SecretKey
}

func (s *S3CompatibleCredentials) GetPathStyleAccessEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.PathStyleAccessEnabled
}

// #region class-body-s3compatiblecredentials
// #endregion class-body-s3compatiblecredentials

type SeqeraComputeCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	AccessKey     *string `json:"accessKey,omitempty"`
	SecretKey     *string `json:"secretKey,omitempty"`
	AssumeRoleArn *string `json:"assumeRoleArn,omitempty"`
}

func (s SeqeraComputeCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SeqeraComputeCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SeqeraComputeCredentials) GetDiscriminator() *string {
	if s == nil {
		return nil
	}
	return s.Discriminator
}

func (s *SeqeraComputeCredentials) GetAccessKey() *string {
	if s == nil {
		return nil
	}
	return s.AccessKey
}

func (s *SeqeraComputeCredentials) GetSecretKey() *string {
	if s == nil {
		return nil
	}
	return s.SecretKey
}

func (s *SeqeraComputeCredentials) GetAssumeRoleArn() *string {
	if s == nil {
		return nil
	}
	return s.AssumeRoleArn
}

type AzureEntraCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	BatchName     *string `json:"batchName,omitempty"`
	StorageName   *string `json:"storageName,omitempty"`
	BatchKey      *string `json:"batchKey,omitempty"`
	StorageKey    *string `json:"storageKey,omitempty"`
	TenantID      *string `json:"tenantId,omitempty"`
	ClientID      *string `json:"clientId,omitempty"`
	ClientSecret  *string `json:"clientSecret,omitempty"`
}

func (a AzureEntraCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureEntraCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureEntraCredentials) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AzureEntraCredentials) GetBatchName() *string {
	if a == nil {
		return nil
	}
	return a.BatchName
}

func (a *AzureEntraCredentials) GetStorageName() *string {
	if a == nil {
		return nil
	}
	return a.StorageName
}

func (a *AzureEntraCredentials) GetBatchKey() *string {
	if a == nil {
		return nil
	}
	return a.BatchKey
}

func (a *AzureEntraCredentials) GetStorageKey() *string {
	if a == nil {
		return nil
	}
	return a.StorageKey
}

func (a *AzureEntraCredentials) GetTenantID() *string {
	if a == nil {
		return nil
	}
	return a.TenantID
}

func (a *AzureEntraCredentials) GetClientID() *string {
	if a == nil {
		return nil
	}
	return a.ClientID
}

func (a *AzureEntraCredentials) GetClientSecret() *string {
	if a == nil {
		return nil
	}
	return a.ClientSecret
}

type AWSCodeCommitCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Username      *string `json:"username,omitempty"`
	Password      *string `json:"password,omitempty"`
	Token         *string `json:"token,omitempty"`
}

func (a AWSCodeCommitCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AWSCodeCommitCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AWSCodeCommitCredentials) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AWSCodeCommitCredentials) GetUsername() *string {
	if a == nil {
		return nil
	}
	return a.Username
}

func (a *AWSCodeCommitCredentials) GetPassword() *string {
	if a == nil {
		return nil
	}
	return a.Password
}

func (a *AWSCodeCommitCredentials) GetToken() *string {
	if a == nil {
		return nil
	}
	return a.Token
}

type TowerAgentCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	ConnectionID  *string `json:"connectionId,omitempty"`
	WorkDir       *string `json:"workDir,omitempty"`
	Shared        *bool   `json:"shared,omitempty"`
}

func (t TowerAgentCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TowerAgentCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TowerAgentCredentials) GetDiscriminator() *string {
	if t == nil {
		return nil
	}
	return t.Discriminator
}

func (t *TowerAgentCredentials) GetConnectionID() *string {
	if t == nil {
		return nil
	}
	return t.ConnectionID
}

func (t *TowerAgentCredentials) GetWorkDir() *string {
	if t == nil {
		return nil
	}
	return t.WorkDir
}

func (t *TowerAgentCredentials) GetShared() *bool {
	if t == nil {
		return nil
	}
	return t.Shared
}

type ContainerRegistryCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	UserName      *string `json:"userName,omitempty"`
	Password      *string `json:"password,omitempty"`
	Registry      *string `json:"registry,omitempty"`
}

func (c ContainerRegistryCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContainerRegistryCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContainerRegistryCredentials) GetDiscriminator() *string {
	if c == nil {
		return nil
	}
	return c.Discriminator
}

func (c *ContainerRegistryCredentials) GetUserName() *string {
	if c == nil {
		return nil
	}
	return c.UserName
}

func (c *ContainerRegistryCredentials) GetPassword() *string {
	if c == nil {
		return nil
	}
	return c.Password
}

func (c *ContainerRegistryCredentials) GetRegistry() *string {
	if c == nil {
		return nil
	}
	return c.Registry
}

type AzureReposCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Username      *string `json:"username,omitempty"`
	Password      *string `json:"password,omitempty"`
	Token         *string `json:"token,omitempty"`
}

func (a AzureReposCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureReposCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureReposCredentials) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AzureReposCredentials) GetUsername() *string {
	if a == nil {
		return nil
	}
	return a.Username
}

func (a *AzureReposCredentials) GetPassword() *string {
	if a == nil {
		return nil
	}
	return a.Password
}

func (a *AzureReposCredentials) GetToken() *string {
	if a == nil {
		return nil
	}
	return a.Token
}

type AzureCloudCredentials struct {
	Discriminator  *string `json:"discriminator,omitempty"`
	BatchName      *string `json:"batchName,omitempty"`
	StorageName    *string `json:"storageName,omitempty"`
	BatchKey       *string `json:"batchKey,omitempty"`
	StorageKey     *string `json:"storageKey,omitempty"`
	SubscriptionID *string `json:"subscriptionId,omitempty"`
	TenantID       *string `json:"tenantId,omitempty"`
	ClientID       *string `json:"clientId,omitempty"`
	ClientSecret   *string `json:"clientSecret,omitempty"`
}

func (a AzureCloudCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureCloudCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureCloudCredentials) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AzureCloudCredentials) GetBatchName() *string {
	if a == nil {
		return nil
	}
	return a.BatchName
}

func (a *AzureCloudCredentials) GetStorageName() *string {
	if a == nil {
		return nil
	}
	return a.StorageName
}

func (a *AzureCloudCredentials) GetBatchKey() *string {
	if a == nil {
		return nil
	}
	return a.BatchKey
}

func (a *AzureCloudCredentials) GetStorageKey() *string {
	if a == nil {
		return nil
	}
	return a.StorageKey
}

func (a *AzureCloudCredentials) GetSubscriptionID() *string {
	if a == nil {
		return nil
	}
	return a.SubscriptionID
}

func (a *AzureCloudCredentials) GetTenantID() *string {
	if a == nil {
		return nil
	}
	return a.TenantID
}

func (a *AzureCloudCredentials) GetClientID() *string {
	if a == nil {
		return nil
	}
	return a.ClientID
}

func (a *AzureCloudCredentials) GetClientSecret() *string {
	if a == nil {
		return nil
	}
	return a.ClientSecret
}

type AzureCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	BatchName     *string `json:"batchName,omitempty"`
	StorageName   *string `json:"storageName,omitempty"`
	BatchKey      *string `json:"batchKey,omitempty"`
	StorageKey    *string `json:"storageKey,omitempty"`
}

func (a AzureCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureCredentials) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AzureCredentials) GetBatchName() *string {
	if a == nil {
		return nil
	}
	return a.BatchName
}

func (a *AzureCredentials) GetStorageName() *string {
	if a == nil {
		return nil
	}
	return a.StorageName
}

func (a *AzureCredentials) GetBatchKey() *string {
	if a == nil {
		return nil
	}
	return a.BatchKey
}

func (a *AzureCredentials) GetStorageKey() *string {
	if a == nil {
		return nil
	}
	return a.StorageKey
}

type KubernetesCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Certificate   *string `json:"certificate,omitempty"`
	PrivateKey    *string `json:"privateKey,omitempty"`
	Token         *string `json:"token,omitempty"`
}

func (k KubernetesCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KubernetesCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KubernetesCredentials) GetDiscriminator() *string {
	if k == nil {
		return nil
	}
	return k.Discriminator
}

func (k *KubernetesCredentials) GetCertificate() *string {
	if k == nil {
		return nil
	}
	return k.Certificate
}

func (k *KubernetesCredentials) GetPrivateKey() *string {
	if k == nil {
		return nil
	}
	return k.PrivateKey
}

func (k *KubernetesCredentials) GetToken() *string {
	if k == nil {
		return nil
	}
	return k.Token
}

type SSHCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	PrivateKey    *string `json:"privateKey,omitempty"`
	Passphrase    *string `json:"passphrase,omitempty"`
}

func (s SSHCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSHCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SSHCredentials) GetDiscriminator() *string {
	if s == nil {
		return nil
	}
	return s.Discriminator
}

func (s *SSHCredentials) GetPrivateKey() *string {
	if s == nil {
		return nil
	}
	return s.PrivateKey
}

func (s *SSHCredentials) GetPassphrase() *string {
	if s == nil {
		return nil
	}
	return s.Passphrase
}

type GiteaCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Username      *string `json:"username,omitempty"`
	Password      *string `json:"password,omitempty"`
	Token         *string `json:"token,omitempty"`
}

func (g GiteaCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GiteaCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GiteaCredentials) GetDiscriminator() *string {
	if g == nil {
		return nil
	}
	return g.Discriminator
}

func (g *GiteaCredentials) GetUsername() *string {
	if g == nil {
		return nil
	}
	return g.Username
}

func (g *GiteaCredentials) GetPassword() *string {
	if g == nil {
		return nil
	}
	return g.Password
}

func (g *GiteaCredentials) GetToken() *string {
	if g == nil {
		return nil
	}
	return g.Token
}

type BitBucketCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Username      *string `json:"username,omitempty"`
	Password      *string `json:"password,omitempty"`
	Token         *string `json:"token,omitempty"`
}

func (b BitBucketCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BitBucketCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BitBucketCredentials) GetDiscriminator() *string {
	if b == nil {
		return nil
	}
	return b.Discriminator
}

func (b *BitBucketCredentials) GetUsername() *string {
	if b == nil {
		return nil
	}
	return b.Username
}

func (b *BitBucketCredentials) GetPassword() *string {
	if b == nil {
		return nil
	}
	return b.Password
}

func (b *BitBucketCredentials) GetToken() *string {
	if b == nil {
		return nil
	}
	return b.Token
}

type GitLabCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Username      *string `json:"username,omitempty"`
	Password      *string `json:"password,omitempty"`
	Token         *string `json:"token,omitempty"`
}

func (g GitLabCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GitLabCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GitLabCredentials) GetDiscriminator() *string {
	if g == nil {
		return nil
	}
	return g.Discriminator
}

func (g *GitLabCredentials) GetUsername() *string {
	if g == nil {
		return nil
	}
	return g.Username
}

func (g *GitLabCredentials) GetPassword() *string {
	if g == nil {
		return nil
	}
	return g.Password
}

func (g *GitLabCredentials) GetToken() *string {
	if g == nil {
		return nil
	}
	return g.Token
}

type GitHubCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Username      *string `json:"username,omitempty"`
	Password      *string `json:"password,omitempty"`
	Token         *string `json:"token,omitempty"`
}

func (g GitHubCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GitHubCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GitHubCredentials) GetDiscriminator() *string {
	if g == nil {
		return nil
	}
	return g.Discriminator
}

func (g *GitHubCredentials) GetUsername() *string {
	if g == nil {
		return nil
	}
	return g.Username
}

func (g *GitHubCredentials) GetPassword() *string {
	if g == nil {
		return nil
	}
	return g.Password
}

func (g *GitHubCredentials) GetToken() *string {
	if g == nil {
		return nil
	}
	return g.Token
}

type GoogleCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Data          *string `json:"data,omitempty"`
}

func (g GoogleCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GoogleCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GoogleCredentials) GetDiscriminator() *string {
	if g == nil {
		return nil
	}
	return g.Discriminator
}

func (g *GoogleCredentials) GetData() *string {
	if g == nil {
		return nil
	}
	return g.Data
}

type AWSCredentials struct {
	Discriminator *string `json:"discriminator,omitempty"`
	AccessKey     *string `json:"accessKey,omitempty"`
	SecretKey     *string `json:"secretKey,omitempty"`
	AssumeRoleArn *string `json:"assumeRoleArn,omitempty"`
}

func (a AWSCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AWSCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AWSCredentials) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AWSCredentials) GetAccessKey() *string {
	if a == nil {
		return nil
	}
	return a.AccessKey
}

func (a *AWSCredentials) GetSecretKey() *string {
	if a == nil {
		return nil
	}
	return a.SecretKey
}

func (a *AWSCredentials) GetAssumeRoleArn() *string {
	if a == nil {
		return nil
	}
	return a.AssumeRoleArn
}

type SecurityKeysType string

const (
	SecurityKeysTypeS3            SecurityKeysType = "s3"
	SecurityKeysTypeGithub        SecurityKeysType = "github"
	SecurityKeysTypeAzurerepos    SecurityKeysType = "azurerepos"
	SecurityKeysTypeAzureEntra    SecurityKeysType = "azure_entra"
	SecurityKeysTypeContainerReg  SecurityKeysType = "container-reg"
	SecurityKeysTypeTwAgent       SecurityKeysType = "tw-agent"
	SecurityKeysTypeK8s           SecurityKeysType = "k8s"
	SecurityKeysTypeSSH           SecurityKeysType = "ssh"
	SecurityKeysTypeGoogle        SecurityKeysType = "google"
	SecurityKeysTypeBitbucket     SecurityKeysType = "bitbucket"
	SecurityKeysTypeAzureCloud    SecurityKeysType = "azure-cloud"
	SecurityKeysTypeLocal         SecurityKeysType = "local"
	SecurityKeysTypeGitea         SecurityKeysType = "gitea"
	SecurityKeysTypeSeqeracompute SecurityKeysType = "seqeracompute"
	SecurityKeysTypeCodecommit    SecurityKeysType = "codecommit"
	SecurityKeysTypeGitlab        SecurityKeysType = "gitlab"
	SecurityKeysTypeAws           SecurityKeysType = "aws"
	SecurityKeysTypeAzure         SecurityKeysType = "azure"
)

type SecurityKeys struct {
	AWSCredentials               *AWSCredentials               `queryParam:"inline" union:"member"`
	GoogleCredentials            *GoogleCredentials            `queryParam:"inline" union:"member"`
	GitHubCredentials            *GitHubCredentials            `queryParam:"inline" union:"member"`
	GitLabCredentials            *GitLabCredentials            `queryParam:"inline" union:"member"`
	BitBucketCredentials         *BitBucketCredentials         `queryParam:"inline" union:"member"`
	GiteaCredentials             *GiteaCredentials             `queryParam:"inline" union:"member"`
	SSHCredentials               *SSHCredentials               `queryParam:"inline" union:"member"`
	KubernetesCredentials        *KubernetesCredentials        `queryParam:"inline" union:"member"`
	AzureCredentials             *AzureCredentials             `queryParam:"inline" union:"member"`
	AzureCloudCredentials        *AzureCloudCredentials        `queryParam:"inline" union:"member"`
	AzureReposCredentials        *AzureReposCredentials        `queryParam:"inline" union:"member"`
	ContainerRegistryCredentials *ContainerRegistryCredentials `queryParam:"inline" union:"member"`
	TowerAgentCredentials        *TowerAgentCredentials        `queryParam:"inline" union:"member"`
	AWSCodeCommitCredentials     *AWSCodeCommitCredentials     `queryParam:"inline" union:"member"`
	AzureEntraCredentials        *AzureEntraCredentials        `queryParam:"inline" union:"member"`
	SeqeraComputeCredentials     *SeqeraComputeCredentials     `queryParam:"inline" union:"member"`
	S3CompatibleCredentials      *S3CompatibleCredentials      `queryParam:"inline" union:"member"`
	LocalSecurityKeys            *LocalSecurityKeys            `queryParam:"inline" union:"member"`

	Type SecurityKeysType
}

func CreateSecurityKeysS3(s3 S3CompatibleCredentials) SecurityKeys {
	typ := SecurityKeysTypeS3

	typStr := string(typ)
	s3.Discriminator = &typStr

	return SecurityKeys{
		S3CompatibleCredentials: &s3,
		Type:                    typ,
	}
}

func CreateSecurityKeysGithub(github GitHubCredentials) SecurityKeys {
	typ := SecurityKeysTypeGithub

	typStr := string(typ)
	github.Discriminator = &typStr

	return SecurityKeys{
		GitHubCredentials: &github,
		Type:              typ,
	}
}

func CreateSecurityKeysAzurerepos(azurerepos AzureReposCredentials) SecurityKeys {
	typ := SecurityKeysTypeAzurerepos

	typStr := string(typ)
	azurerepos.Discriminator = &typStr

	return SecurityKeys{
		AzureReposCredentials: &azurerepos,
		Type:                  typ,
	}
}

func CreateSecurityKeysAzureEntra(azureEntra AzureEntraCredentials) SecurityKeys {
	typ := SecurityKeysTypeAzureEntra

	typStr := string(typ)
	azureEntra.Discriminator = &typStr

	return SecurityKeys{
		AzureEntraCredentials: &azureEntra,
		Type:                  typ,
	}
}

func CreateSecurityKeysContainerReg(containerReg ContainerRegistryCredentials) SecurityKeys {
	typ := SecurityKeysTypeContainerReg

	typStr := string(typ)
	containerReg.Discriminator = &typStr

	return SecurityKeys{
		ContainerRegistryCredentials: &containerReg,
		Type:                         typ,
	}
}

func CreateSecurityKeysTwAgent(twAgent TowerAgentCredentials) SecurityKeys {
	typ := SecurityKeysTypeTwAgent

	typStr := string(typ)
	twAgent.Discriminator = &typStr

	return SecurityKeys{
		TowerAgentCredentials: &twAgent,
		Type:                  typ,
	}
}

func CreateSecurityKeysK8s(k8s KubernetesCredentials) SecurityKeys {
	typ := SecurityKeysTypeK8s

	typStr := string(typ)
	k8s.Discriminator = &typStr

	return SecurityKeys{
		KubernetesCredentials: &k8s,
		Type:                  typ,
	}
}

func CreateSecurityKeysSSH(ssh SSHCredentials) SecurityKeys {
	typ := SecurityKeysTypeSSH

	typStr := string(typ)
	ssh.Discriminator = &typStr

	return SecurityKeys{
		SSHCredentials: &ssh,
		Type:           typ,
	}
}

func CreateSecurityKeysGoogle(google GoogleCredentials) SecurityKeys {
	typ := SecurityKeysTypeGoogle

	typStr := string(typ)
	google.Discriminator = &typStr

	return SecurityKeys{
		GoogleCredentials: &google,
		Type:              typ,
	}
}

func CreateSecurityKeysBitbucket(bitbucket BitBucketCredentials) SecurityKeys {
	typ := SecurityKeysTypeBitbucket

	typStr := string(typ)
	bitbucket.Discriminator = &typStr

	return SecurityKeys{
		BitBucketCredentials: &bitbucket,
		Type:                 typ,
	}
}

func CreateSecurityKeysAzureCloud(azureCloud AzureCloudCredentials) SecurityKeys {
	typ := SecurityKeysTypeAzureCloud

	typStr := string(typ)
	azureCloud.Discriminator = &typStr

	return SecurityKeys{
		AzureCloudCredentials: &azureCloud,
		Type:                  typ,
	}
}

func CreateSecurityKeysLocal(local LocalSecurityKeys) SecurityKeys {
	typ := SecurityKeysTypeLocal

	typStr := string(typ)
	local.Discriminator = &typStr

	return SecurityKeys{
		LocalSecurityKeys: &local,
		Type:              typ,
	}
}

func CreateSecurityKeysGitea(gitea GiteaCredentials) SecurityKeys {
	typ := SecurityKeysTypeGitea

	typStr := string(typ)
	gitea.Discriminator = &typStr

	return SecurityKeys{
		GiteaCredentials: &gitea,
		Type:             typ,
	}
}

func CreateSecurityKeysSeqeracompute(seqeracompute SeqeraComputeCredentials) SecurityKeys {
	typ := SecurityKeysTypeSeqeracompute

	typStr := string(typ)
	seqeracompute.Discriminator = &typStr

	return SecurityKeys{
		SeqeraComputeCredentials: &seqeracompute,
		Type:                     typ,
	}
}

func CreateSecurityKeysCodecommit(codecommit AWSCodeCommitCredentials) SecurityKeys {
	typ := SecurityKeysTypeCodecommit

	typStr := string(typ)
	codecommit.Discriminator = &typStr

	return SecurityKeys{
		AWSCodeCommitCredentials: &codecommit,
		Type:                     typ,
	}
}

func CreateSecurityKeysGitlab(gitlab GitLabCredentials) SecurityKeys {
	typ := SecurityKeysTypeGitlab

	typStr := string(typ)
	gitlab.Discriminator = &typStr

	return SecurityKeys{
		GitLabCredentials: &gitlab,
		Type:              typ,
	}
}

func CreateSecurityKeysAws(aws AWSCredentials) SecurityKeys {
	typ := SecurityKeysTypeAws

	typStr := string(typ)
	aws.Discriminator = &typStr

	return SecurityKeys{
		AWSCredentials: &aws,
		Type:           typ,
	}
}

func CreateSecurityKeysAzure(azure AzureCredentials) SecurityKeys {
	typ := SecurityKeysTypeAzure

	typStr := string(typ)
	azure.Discriminator = &typStr

	return SecurityKeys{
		AzureCredentials: &azure,
		Type:             typ,
	}
}

func (u *SecurityKeys) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Discriminator string `json:"discriminator"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Discriminator {
	case "s3":
		s3CompatibleCredentials := new(S3CompatibleCredentials)
		if err := utils.UnmarshalJSON(data, &s3CompatibleCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == s3) type S3CompatibleCredentials within SecurityKeys: %w", string(data), err)
		}

		u.S3CompatibleCredentials = s3CompatibleCredentials
		u.Type = SecurityKeysTypeS3
		return nil
	case "github":
		gitHubCredentials := new(GitHubCredentials)
		if err := utils.UnmarshalJSON(data, &gitHubCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == github) type GitHubCredentials within SecurityKeys: %w", string(data), err)
		}

		u.GitHubCredentials = gitHubCredentials
		u.Type = SecurityKeysTypeGithub
		return nil
	case "azurerepos":
		azureReposCredentials := new(AzureReposCredentials)
		if err := utils.UnmarshalJSON(data, &azureReposCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == azurerepos) type AzureReposCredentials within SecurityKeys: %w", string(data), err)
		}

		u.AzureReposCredentials = azureReposCredentials
		u.Type = SecurityKeysTypeAzurerepos
		return nil
	case "azure_entra":
		azureEntraCredentials := new(AzureEntraCredentials)
		if err := utils.UnmarshalJSON(data, &azureEntraCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == azure_entra) type AzureEntraCredentials within SecurityKeys: %w", string(data), err)
		}

		u.AzureEntraCredentials = azureEntraCredentials
		u.Type = SecurityKeysTypeAzureEntra
		return nil
	case "container-reg":
		containerRegistryCredentials := new(ContainerRegistryCredentials)
		if err := utils.UnmarshalJSON(data, &containerRegistryCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == container-reg) type ContainerRegistryCredentials within SecurityKeys: %w", string(data), err)
		}

		u.ContainerRegistryCredentials = containerRegistryCredentials
		u.Type = SecurityKeysTypeContainerReg
		return nil
	case "tw-agent":
		towerAgentCredentials := new(TowerAgentCredentials)
		if err := utils.UnmarshalJSON(data, &towerAgentCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == tw-agent) type TowerAgentCredentials within SecurityKeys: %w", string(data), err)
		}

		u.TowerAgentCredentials = towerAgentCredentials
		u.Type = SecurityKeysTypeTwAgent
		return nil
	case "k8s":
		kubernetesCredentials := new(KubernetesCredentials)
		if err := utils.UnmarshalJSON(data, &kubernetesCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == k8s) type KubernetesCredentials within SecurityKeys: %w", string(data), err)
		}

		u.KubernetesCredentials = kubernetesCredentials
		u.Type = SecurityKeysTypeK8s
		return nil
	case "ssh":
		sshCredentials := new(SSHCredentials)
		if err := utils.UnmarshalJSON(data, &sshCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == ssh) type SSHCredentials within SecurityKeys: %w", string(data), err)
		}

		u.SSHCredentials = sshCredentials
		u.Type = SecurityKeysTypeSSH
		return nil
	case "google":
		googleCredentials := new(GoogleCredentials)
		if err := utils.UnmarshalJSON(data, &googleCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == google) type GoogleCredentials within SecurityKeys: %w", string(data), err)
		}

		u.GoogleCredentials = googleCredentials
		u.Type = SecurityKeysTypeGoogle
		return nil
	case "bitbucket":
		bitBucketCredentials := new(BitBucketCredentials)
		if err := utils.UnmarshalJSON(data, &bitBucketCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == bitbucket) type BitBucketCredentials within SecurityKeys: %w", string(data), err)
		}

		u.BitBucketCredentials = bitBucketCredentials
		u.Type = SecurityKeysTypeBitbucket
		return nil
	case "azure-cloud":
		azureCloudCredentials := new(AzureCloudCredentials)
		if err := utils.UnmarshalJSON(data, &azureCloudCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == azure-cloud) type AzureCloudCredentials within SecurityKeys: %w", string(data), err)
		}

		u.AzureCloudCredentials = azureCloudCredentials
		u.Type = SecurityKeysTypeAzureCloud
		return nil
	case "local":
		localSecurityKeys := new(LocalSecurityKeys)
		if err := utils.UnmarshalJSON(data, &localSecurityKeys, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == local) type LocalSecurityKeys within SecurityKeys: %w", string(data), err)
		}

		u.LocalSecurityKeys = localSecurityKeys
		u.Type = SecurityKeysTypeLocal
		return nil
	case "gitea":
		giteaCredentials := new(GiteaCredentials)
		if err := utils.UnmarshalJSON(data, &giteaCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == gitea) type GiteaCredentials within SecurityKeys: %w", string(data), err)
		}

		u.GiteaCredentials = giteaCredentials
		u.Type = SecurityKeysTypeGitea
		return nil
	case "seqeracompute":
		seqeraComputeCredentials := new(SeqeraComputeCredentials)
		if err := utils.UnmarshalJSON(data, &seqeraComputeCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == seqeracompute) type SeqeraComputeCredentials within SecurityKeys: %w", string(data), err)
		}

		u.SeqeraComputeCredentials = seqeraComputeCredentials
		u.Type = SecurityKeysTypeSeqeracompute
		return nil
	case "codecommit":
		awsCodeCommitCredentials := new(AWSCodeCommitCredentials)
		if err := utils.UnmarshalJSON(data, &awsCodeCommitCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == codecommit) type AWSCodeCommitCredentials within SecurityKeys: %w", string(data), err)
		}

		u.AWSCodeCommitCredentials = awsCodeCommitCredentials
		u.Type = SecurityKeysTypeCodecommit
		return nil
	case "gitlab":
		gitLabCredentials := new(GitLabCredentials)
		if err := utils.UnmarshalJSON(data, &gitLabCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == gitlab) type GitLabCredentials within SecurityKeys: %w", string(data), err)
		}

		u.GitLabCredentials = gitLabCredentials
		u.Type = SecurityKeysTypeGitlab
		return nil
	case "aws":
		awsCredentials := new(AWSCredentials)
		if err := utils.UnmarshalJSON(data, &awsCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == aws) type AWSCredentials within SecurityKeys: %w", string(data), err)
		}

		u.AWSCredentials = awsCredentials
		u.Type = SecurityKeysTypeAws
		return nil
	case "azure":
		azureCredentials := new(AzureCredentials)
		if err := utils.UnmarshalJSON(data, &azureCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == azure) type AzureCredentials within SecurityKeys: %w", string(data), err)
		}

		u.AzureCredentials = azureCredentials
		u.Type = SecurityKeysTypeAzure
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SecurityKeys", string(data))
}

func (u SecurityKeys) MarshalJSON() ([]byte, error) {
	if u.AWSCredentials != nil {
		return utils.MarshalJSON(u.AWSCredentials, "", true)
	}

	if u.GoogleCredentials != nil {
		return utils.MarshalJSON(u.GoogleCredentials, "", true)
	}

	if u.GitHubCredentials != nil {
		return utils.MarshalJSON(u.GitHubCredentials, "", true)
	}

	if u.GitLabCredentials != nil {
		return utils.MarshalJSON(u.GitLabCredentials, "", true)
	}

	if u.BitBucketCredentials != nil {
		return utils.MarshalJSON(u.BitBucketCredentials, "", true)
	}

	if u.GiteaCredentials != nil {
		return utils.MarshalJSON(u.GiteaCredentials, "", true)
	}

	if u.SSHCredentials != nil {
		return utils.MarshalJSON(u.SSHCredentials, "", true)
	}

	if u.KubernetesCredentials != nil {
		return utils.MarshalJSON(u.KubernetesCredentials, "", true)
	}

	if u.AzureCredentials != nil {
		return utils.MarshalJSON(u.AzureCredentials, "", true)
	}

	if u.AzureCloudCredentials != nil {
		return utils.MarshalJSON(u.AzureCloudCredentials, "", true)
	}

	if u.AzureReposCredentials != nil {
		return utils.MarshalJSON(u.AzureReposCredentials, "", true)
	}

	if u.ContainerRegistryCredentials != nil {
		return utils.MarshalJSON(u.ContainerRegistryCredentials, "", true)
	}

	if u.TowerAgentCredentials != nil {
		return utils.MarshalJSON(u.TowerAgentCredentials, "", true)
	}

	if u.AWSCodeCommitCredentials != nil {
		return utils.MarshalJSON(u.AWSCodeCommitCredentials, "", true)
	}

	if u.AzureEntraCredentials != nil {
		return utils.MarshalJSON(u.AzureEntraCredentials, "", true)
	}

	if u.SeqeraComputeCredentials != nil {
		return utils.MarshalJSON(u.SeqeraComputeCredentials, "", true)
	}

	if u.S3CompatibleCredentials != nil {
		return utils.MarshalJSON(u.S3CompatibleCredentials, "", true)
	}

	if u.LocalSecurityKeys != nil {
		return utils.MarshalJSON(u.LocalSecurityKeys, "", true)
	}

	return nil, errors.New("could not marshal union type SecurityKeys: all fields are null")
}

type LocalSecurityKeysOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
}

func (l LocalSecurityKeysOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LocalSecurityKeysOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LocalSecurityKeysOutput) GetDiscriminator() *string {
	if l == nil {
		return nil
	}
	return l.Discriminator
}

type S3CompatibleCredentialsOutput struct {
	Discriminator          *string `json:"discriminator,omitempty"`
	AccessKey              *string `json:"accessKey,omitempty"`
	PathStyleAccessEnabled *bool   `json:"pathStyleAccessEnabled,omitempty"`
}

func (s S3CompatibleCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *S3CompatibleCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *S3CompatibleCredentialsOutput) GetDiscriminator() *string {
	if s == nil {
		return nil
	}
	return s.Discriminator
}

func (s *S3CompatibleCredentialsOutput) GetAccessKey() *string {
	if s == nil {
		return nil
	}
	return s.AccessKey
}

func (s *S3CompatibleCredentialsOutput) GetPathStyleAccessEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.PathStyleAccessEnabled
}

// #region class-body-s3compatiblecredentialsoutput
// #endregion class-body-s3compatiblecredentialsoutput

type SeqeraComputeCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
	AccessKey     *string `json:"accessKey,omitempty"`
	AssumeRoleArn *string `json:"assumeRoleArn,omitempty"`
}

func (s SeqeraComputeCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SeqeraComputeCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SeqeraComputeCredentialsOutput) GetDiscriminator() *string {
	if s == nil {
		return nil
	}
	return s.Discriminator
}

func (s *SeqeraComputeCredentialsOutput) GetAccessKey() *string {
	if s == nil {
		return nil
	}
	return s.AccessKey
}

func (s *SeqeraComputeCredentialsOutput) GetAssumeRoleArn() *string {
	if s == nil {
		return nil
	}
	return s.AssumeRoleArn
}

type AzureEntraCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
	BatchName     *string `json:"batchName,omitempty"`
	StorageName   *string `json:"storageName,omitempty"`
	TenantID      *string `json:"tenantId,omitempty"`
	ClientID      *string `json:"clientId,omitempty"`
}

func (a AzureEntraCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureEntraCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureEntraCredentialsOutput) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AzureEntraCredentialsOutput) GetBatchName() *string {
	if a == nil {
		return nil
	}
	return a.BatchName
}

func (a *AzureEntraCredentialsOutput) GetStorageName() *string {
	if a == nil {
		return nil
	}
	return a.StorageName
}

func (a *AzureEntraCredentialsOutput) GetTenantID() *string {
	if a == nil {
		return nil
	}
	return a.TenantID
}

func (a *AzureEntraCredentialsOutput) GetClientID() *string {
	if a == nil {
		return nil
	}
	return a.ClientID
}

type AWSCodeCommitCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Username      *string `json:"username,omitempty"`
	Token         *string `json:"token,omitempty"`
}

func (a AWSCodeCommitCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AWSCodeCommitCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AWSCodeCommitCredentialsOutput) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AWSCodeCommitCredentialsOutput) GetUsername() *string {
	if a == nil {
		return nil
	}
	return a.Username
}

func (a *AWSCodeCommitCredentialsOutput) GetToken() *string {
	if a == nil {
		return nil
	}
	return a.Token
}

type ContainerRegistryCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
	UserName      *string `json:"userName,omitempty"`
	Registry      *string `json:"registry,omitempty"`
}

func (c ContainerRegistryCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContainerRegistryCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContainerRegistryCredentialsOutput) GetDiscriminator() *string {
	if c == nil {
		return nil
	}
	return c.Discriminator
}

func (c *ContainerRegistryCredentialsOutput) GetUserName() *string {
	if c == nil {
		return nil
	}
	return c.UserName
}

func (c *ContainerRegistryCredentialsOutput) GetRegistry() *string {
	if c == nil {
		return nil
	}
	return c.Registry
}

type AzureReposCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Username      *string `json:"username,omitempty"`
}

func (a AzureReposCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureReposCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureReposCredentialsOutput) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AzureReposCredentialsOutput) GetUsername() *string {
	if a == nil {
		return nil
	}
	return a.Username
}

type AzureCloudCredentialsOutput struct {
	Discriminator  *string `json:"discriminator,omitempty"`
	BatchName      *string `json:"batchName,omitempty"`
	StorageName    *string `json:"storageName,omitempty"`
	SubscriptionID *string `json:"subscriptionId,omitempty"`
	TenantID       *string `json:"tenantId,omitempty"`
	ClientID       *string `json:"clientId,omitempty"`
}

func (a AzureCloudCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureCloudCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureCloudCredentialsOutput) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AzureCloudCredentialsOutput) GetBatchName() *string {
	if a == nil {
		return nil
	}
	return a.BatchName
}

func (a *AzureCloudCredentialsOutput) GetStorageName() *string {
	if a == nil {
		return nil
	}
	return a.StorageName
}

func (a *AzureCloudCredentialsOutput) GetSubscriptionID() *string {
	if a == nil {
		return nil
	}
	return a.SubscriptionID
}

func (a *AzureCloudCredentialsOutput) GetTenantID() *string {
	if a == nil {
		return nil
	}
	return a.TenantID
}

func (a *AzureCloudCredentialsOutput) GetClientID() *string {
	if a == nil {
		return nil
	}
	return a.ClientID
}

type AzureCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
	BatchName     *string `json:"batchName,omitempty"`
	StorageName   *string `json:"storageName,omitempty"`
}

func (a AzureCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureCredentialsOutput) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AzureCredentialsOutput) GetBatchName() *string {
	if a == nil {
		return nil
	}
	return a.BatchName
}

func (a *AzureCredentialsOutput) GetStorageName() *string {
	if a == nil {
		return nil
	}
	return a.StorageName
}

type KubernetesCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
}

func (k KubernetesCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KubernetesCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KubernetesCredentialsOutput) GetDiscriminator() *string {
	if k == nil {
		return nil
	}
	return k.Discriminator
}

type SSHCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
}

func (s SSHCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSHCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SSHCredentialsOutput) GetDiscriminator() *string {
	if s == nil {
		return nil
	}
	return s.Discriminator
}

type GiteaCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Username      *string `json:"username,omitempty"`
}

func (g GiteaCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GiteaCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GiteaCredentialsOutput) GetDiscriminator() *string {
	if g == nil {
		return nil
	}
	return g.Discriminator
}

func (g *GiteaCredentialsOutput) GetUsername() *string {
	if g == nil {
		return nil
	}
	return g.Username
}

type BitBucketCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Username      *string `json:"username,omitempty"`
}

func (b BitBucketCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BitBucketCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BitBucketCredentialsOutput) GetDiscriminator() *string {
	if b == nil {
		return nil
	}
	return b.Discriminator
}

func (b *BitBucketCredentialsOutput) GetUsername() *string {
	if b == nil {
		return nil
	}
	return b.Username
}

type GitLabCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Username      *string `json:"username,omitempty"`
}

func (g GitLabCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GitLabCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GitLabCredentialsOutput) GetDiscriminator() *string {
	if g == nil {
		return nil
	}
	return g.Discriminator
}

func (g *GitLabCredentialsOutput) GetUsername() *string {
	if g == nil {
		return nil
	}
	return g.Username
}

type GitHubCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
	Username      *string `json:"username,omitempty"`
}

func (g GitHubCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GitHubCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GitHubCredentialsOutput) GetDiscriminator() *string {
	if g == nil {
		return nil
	}
	return g.Discriminator
}

func (g *GitHubCredentialsOutput) GetUsername() *string {
	if g == nil {
		return nil
	}
	return g.Username
}

type GoogleCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
}

func (g GoogleCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GoogleCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GoogleCredentialsOutput) GetDiscriminator() *string {
	if g == nil {
		return nil
	}
	return g.Discriminator
}

type AWSCredentialsOutput struct {
	Discriminator *string `json:"discriminator,omitempty"`
	AccessKey     *string `json:"accessKey,omitempty"`
	AssumeRoleArn *string `json:"assumeRoleArn,omitempty"`
}

func (a AWSCredentialsOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AWSCredentialsOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AWSCredentialsOutput) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AWSCredentialsOutput) GetAccessKey() *string {
	if a == nil {
		return nil
	}
	return a.AccessKey
}

func (a *AWSCredentialsOutput) GetAssumeRoleArn() *string {
	if a == nil {
		return nil
	}
	return a.AssumeRoleArn
}

type SecurityKeysOutputType string

const (
	SecurityKeysOutputTypeS3            SecurityKeysOutputType = "s3"
	SecurityKeysOutputTypeGithub        SecurityKeysOutputType = "github"
	SecurityKeysOutputTypeAzurerepos    SecurityKeysOutputType = "azurerepos"
	SecurityKeysOutputTypeAzureEntra    SecurityKeysOutputType = "azure_entra"
	SecurityKeysOutputTypeContainerReg  SecurityKeysOutputType = "container-reg"
	SecurityKeysOutputTypeTwAgent       SecurityKeysOutputType = "tw-agent"
	SecurityKeysOutputTypeK8s           SecurityKeysOutputType = "k8s"
	SecurityKeysOutputTypeSSH           SecurityKeysOutputType = "ssh"
	SecurityKeysOutputTypeGoogle        SecurityKeysOutputType = "google"
	SecurityKeysOutputTypeBitbucket     SecurityKeysOutputType = "bitbucket"
	SecurityKeysOutputTypeAzureCloud    SecurityKeysOutputType = "azure-cloud"
	SecurityKeysOutputTypeLocal         SecurityKeysOutputType = "local"
	SecurityKeysOutputTypeGitea         SecurityKeysOutputType = "gitea"
	SecurityKeysOutputTypeSeqeracompute SecurityKeysOutputType = "seqeracompute"
	SecurityKeysOutputTypeCodecommit    SecurityKeysOutputType = "codecommit"
	SecurityKeysOutputTypeGitlab        SecurityKeysOutputType = "gitlab"
	SecurityKeysOutputTypeAws           SecurityKeysOutputType = "aws"
	SecurityKeysOutputTypeAzure         SecurityKeysOutputType = "azure"
)

type SecurityKeysOutput struct {
	AWSCredentialsOutput               *AWSCredentialsOutput               `queryParam:"inline" union:"member"`
	GoogleCredentialsOutput            *GoogleCredentialsOutput            `queryParam:"inline" union:"member"`
	GitHubCredentialsOutput            *GitHubCredentialsOutput            `queryParam:"inline" union:"member"`
	GitLabCredentialsOutput            *GitLabCredentialsOutput            `queryParam:"inline" union:"member"`
	BitBucketCredentialsOutput         *BitBucketCredentialsOutput         `queryParam:"inline" union:"member"`
	GiteaCredentialsOutput             *GiteaCredentialsOutput             `queryParam:"inline" union:"member"`
	SSHCredentialsOutput               *SSHCredentialsOutput               `queryParam:"inline" union:"member"`
	KubernetesCredentialsOutput        *KubernetesCredentialsOutput        `queryParam:"inline" union:"member"`
	AzureCredentialsOutput             *AzureCredentialsOutput             `queryParam:"inline" union:"member"`
	AzureCloudCredentialsOutput        *AzureCloudCredentialsOutput        `queryParam:"inline" union:"member"`
	AzureReposCredentialsOutput        *AzureReposCredentialsOutput        `queryParam:"inline" union:"member"`
	ContainerRegistryCredentialsOutput *ContainerRegistryCredentialsOutput `queryParam:"inline" union:"member"`
	TowerAgentCredentials              *TowerAgentCredentials              `queryParam:"inline" union:"member"`
	AWSCodeCommitCredentialsOutput     *AWSCodeCommitCredentialsOutput     `queryParam:"inline" union:"member"`
	AzureEntraCredentialsOutput        *AzureEntraCredentialsOutput        `queryParam:"inline" union:"member"`
	SeqeraComputeCredentialsOutput     *SeqeraComputeCredentialsOutput     `queryParam:"inline" union:"member"`
	S3CompatibleCredentialsOutput      *S3CompatibleCredentialsOutput      `queryParam:"inline" union:"member"`
	LocalSecurityKeysOutput            *LocalSecurityKeysOutput            `queryParam:"inline" union:"member"`

	Type SecurityKeysOutputType
}

func CreateSecurityKeysOutputS3(s3 S3CompatibleCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeS3

	typStr := string(typ)
	s3.Discriminator = &typStr

	return SecurityKeysOutput{
		S3CompatibleCredentialsOutput: &s3,
		Type:                          typ,
	}
}

func CreateSecurityKeysOutputGithub(github GitHubCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeGithub

	typStr := string(typ)
	github.Discriminator = &typStr

	return SecurityKeysOutput{
		GitHubCredentialsOutput: &github,
		Type:                    typ,
	}
}

func CreateSecurityKeysOutputAzurerepos(azurerepos AzureReposCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeAzurerepos

	typStr := string(typ)
	azurerepos.Discriminator = &typStr

	return SecurityKeysOutput{
		AzureReposCredentialsOutput: &azurerepos,
		Type:                        typ,
	}
}

func CreateSecurityKeysOutputAzureEntra(azureEntra AzureEntraCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeAzureEntra

	typStr := string(typ)
	azureEntra.Discriminator = &typStr

	return SecurityKeysOutput{
		AzureEntraCredentialsOutput: &azureEntra,
		Type:                        typ,
	}
}

func CreateSecurityKeysOutputContainerReg(containerReg ContainerRegistryCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeContainerReg

	typStr := string(typ)
	containerReg.Discriminator = &typStr

	return SecurityKeysOutput{
		ContainerRegistryCredentialsOutput: &containerReg,
		Type:                               typ,
	}
}

func CreateSecurityKeysOutputTwAgent(twAgent TowerAgentCredentials) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeTwAgent

	typStr := string(typ)
	twAgent.Discriminator = &typStr

	return SecurityKeysOutput{
		TowerAgentCredentials: &twAgent,
		Type:                  typ,
	}
}

func CreateSecurityKeysOutputK8s(k8s KubernetesCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeK8s

	typStr := string(typ)
	k8s.Discriminator = &typStr

	return SecurityKeysOutput{
		KubernetesCredentialsOutput: &k8s,
		Type:                        typ,
	}
}

func CreateSecurityKeysOutputSSH(ssh SSHCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeSSH

	typStr := string(typ)
	ssh.Discriminator = &typStr

	return SecurityKeysOutput{
		SSHCredentialsOutput: &ssh,
		Type:                 typ,
	}
}

func CreateSecurityKeysOutputGoogle(google GoogleCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeGoogle

	typStr := string(typ)
	google.Discriminator = &typStr

	return SecurityKeysOutput{
		GoogleCredentialsOutput: &google,
		Type:                    typ,
	}
}

func CreateSecurityKeysOutputBitbucket(bitbucket BitBucketCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeBitbucket

	typStr := string(typ)
	bitbucket.Discriminator = &typStr

	return SecurityKeysOutput{
		BitBucketCredentialsOutput: &bitbucket,
		Type:                       typ,
	}
}

func CreateSecurityKeysOutputAzureCloud(azureCloud AzureCloudCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeAzureCloud

	typStr := string(typ)
	azureCloud.Discriminator = &typStr

	return SecurityKeysOutput{
		AzureCloudCredentialsOutput: &azureCloud,
		Type:                        typ,
	}
}

func CreateSecurityKeysOutputLocal(local LocalSecurityKeysOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeLocal

	typStr := string(typ)
	local.Discriminator = &typStr

	return SecurityKeysOutput{
		LocalSecurityKeysOutput: &local,
		Type:                    typ,
	}
}

func CreateSecurityKeysOutputGitea(gitea GiteaCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeGitea

	typStr := string(typ)
	gitea.Discriminator = &typStr

	return SecurityKeysOutput{
		GiteaCredentialsOutput: &gitea,
		Type:                   typ,
	}
}

func CreateSecurityKeysOutputSeqeracompute(seqeracompute SeqeraComputeCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeSeqeracompute

	typStr := string(typ)
	seqeracompute.Discriminator = &typStr

	return SecurityKeysOutput{
		SeqeraComputeCredentialsOutput: &seqeracompute,
		Type:                           typ,
	}
}

func CreateSecurityKeysOutputCodecommit(codecommit AWSCodeCommitCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeCodecommit

	typStr := string(typ)
	codecommit.Discriminator = &typStr

	return SecurityKeysOutput{
		AWSCodeCommitCredentialsOutput: &codecommit,
		Type:                           typ,
	}
}

func CreateSecurityKeysOutputGitlab(gitlab GitLabCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeGitlab

	typStr := string(typ)
	gitlab.Discriminator = &typStr

	return SecurityKeysOutput{
		GitLabCredentialsOutput: &gitlab,
		Type:                    typ,
	}
}

func CreateSecurityKeysOutputAws(aws AWSCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeAws

	typStr := string(typ)
	aws.Discriminator = &typStr

	return SecurityKeysOutput{
		AWSCredentialsOutput: &aws,
		Type:                 typ,
	}
}

func CreateSecurityKeysOutputAzure(azure AzureCredentialsOutput) SecurityKeysOutput {
	typ := SecurityKeysOutputTypeAzure

	typStr := string(typ)
	azure.Discriminator = &typStr

	return SecurityKeysOutput{
		AzureCredentialsOutput: &azure,
		Type:                   typ,
	}
}

func (u *SecurityKeysOutput) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Discriminator string `json:"discriminator"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Discriminator {
	case "s3":
		s3CompatibleCredentialsOutput := new(S3CompatibleCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &s3CompatibleCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == s3) type S3CompatibleCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.S3CompatibleCredentialsOutput = s3CompatibleCredentialsOutput
		u.Type = SecurityKeysOutputTypeS3
		return nil
	case "github":
		gitHubCredentialsOutput := new(GitHubCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &gitHubCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == github) type GitHubCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.GitHubCredentialsOutput = gitHubCredentialsOutput
		u.Type = SecurityKeysOutputTypeGithub
		return nil
	case "azurerepos":
		azureReposCredentialsOutput := new(AzureReposCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &azureReposCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == azurerepos) type AzureReposCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.AzureReposCredentialsOutput = azureReposCredentialsOutput
		u.Type = SecurityKeysOutputTypeAzurerepos
		return nil
	case "azure_entra":
		azureEntraCredentialsOutput := new(AzureEntraCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &azureEntraCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == azure_entra) type AzureEntraCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.AzureEntraCredentialsOutput = azureEntraCredentialsOutput
		u.Type = SecurityKeysOutputTypeAzureEntra
		return nil
	case "container-reg":
		containerRegistryCredentialsOutput := new(ContainerRegistryCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &containerRegistryCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == container-reg) type ContainerRegistryCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.ContainerRegistryCredentialsOutput = containerRegistryCredentialsOutput
		u.Type = SecurityKeysOutputTypeContainerReg
		return nil
	case "tw-agent":
		towerAgentCredentials := new(TowerAgentCredentials)
		if err := utils.UnmarshalJSON(data, &towerAgentCredentials, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == tw-agent) type TowerAgentCredentials within SecurityKeysOutput: %w", string(data), err)
		}

		u.TowerAgentCredentials = towerAgentCredentials
		u.Type = SecurityKeysOutputTypeTwAgent
		return nil
	case "k8s":
		kubernetesCredentialsOutput := new(KubernetesCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &kubernetesCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == k8s) type KubernetesCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.KubernetesCredentialsOutput = kubernetesCredentialsOutput
		u.Type = SecurityKeysOutputTypeK8s
		return nil
	case "ssh":
		sshCredentialsOutput := new(SSHCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &sshCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == ssh) type SSHCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.SSHCredentialsOutput = sshCredentialsOutput
		u.Type = SecurityKeysOutputTypeSSH
		return nil
	case "google":
		googleCredentialsOutput := new(GoogleCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &googleCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == google) type GoogleCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.GoogleCredentialsOutput = googleCredentialsOutput
		u.Type = SecurityKeysOutputTypeGoogle
		return nil
	case "bitbucket":
		bitBucketCredentialsOutput := new(BitBucketCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &bitBucketCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == bitbucket) type BitBucketCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.BitBucketCredentialsOutput = bitBucketCredentialsOutput
		u.Type = SecurityKeysOutputTypeBitbucket
		return nil
	case "azure-cloud":
		azureCloudCredentialsOutput := new(AzureCloudCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &azureCloudCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == azure-cloud) type AzureCloudCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.AzureCloudCredentialsOutput = azureCloudCredentialsOutput
		u.Type = SecurityKeysOutputTypeAzureCloud
		return nil
	case "local":
		localSecurityKeysOutput := new(LocalSecurityKeysOutput)
		if err := utils.UnmarshalJSON(data, &localSecurityKeysOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == local) type LocalSecurityKeysOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.LocalSecurityKeysOutput = localSecurityKeysOutput
		u.Type = SecurityKeysOutputTypeLocal
		return nil
	case "gitea":
		giteaCredentialsOutput := new(GiteaCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &giteaCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == gitea) type GiteaCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.GiteaCredentialsOutput = giteaCredentialsOutput
		u.Type = SecurityKeysOutputTypeGitea
		return nil
	case "seqeracompute":
		seqeraComputeCredentialsOutput := new(SeqeraComputeCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &seqeraComputeCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == seqeracompute) type SeqeraComputeCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.SeqeraComputeCredentialsOutput = seqeraComputeCredentialsOutput
		u.Type = SecurityKeysOutputTypeSeqeracompute
		return nil
	case "codecommit":
		awsCodeCommitCredentialsOutput := new(AWSCodeCommitCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &awsCodeCommitCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == codecommit) type AWSCodeCommitCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.AWSCodeCommitCredentialsOutput = awsCodeCommitCredentialsOutput
		u.Type = SecurityKeysOutputTypeCodecommit
		return nil
	case "gitlab":
		gitLabCredentialsOutput := new(GitLabCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &gitLabCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == gitlab) type GitLabCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.GitLabCredentialsOutput = gitLabCredentialsOutput
		u.Type = SecurityKeysOutputTypeGitlab
		return nil
	case "aws":
		awsCredentialsOutput := new(AWSCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &awsCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == aws) type AWSCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.AWSCredentialsOutput = awsCredentialsOutput
		u.Type = SecurityKeysOutputTypeAws
		return nil
	case "azure":
		azureCredentialsOutput := new(AzureCredentialsOutput)
		if err := utils.UnmarshalJSON(data, &azureCredentialsOutput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Discriminator == azure) type AzureCredentialsOutput within SecurityKeysOutput: %w", string(data), err)
		}

		u.AzureCredentialsOutput = azureCredentialsOutput
		u.Type = SecurityKeysOutputTypeAzure
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SecurityKeysOutput", string(data))
}

func (u SecurityKeysOutput) MarshalJSON() ([]byte, error) {
	if u.AWSCredentialsOutput != nil {
		return utils.MarshalJSON(u.AWSCredentialsOutput, "", true)
	}

	if u.GoogleCredentialsOutput != nil {
		return utils.MarshalJSON(u.GoogleCredentialsOutput, "", true)
	}

	if u.GitHubCredentialsOutput != nil {
		return utils.MarshalJSON(u.GitHubCredentialsOutput, "", true)
	}

	if u.GitLabCredentialsOutput != nil {
		return utils.MarshalJSON(u.GitLabCredentialsOutput, "", true)
	}

	if u.BitBucketCredentialsOutput != nil {
		return utils.MarshalJSON(u.BitBucketCredentialsOutput, "", true)
	}

	if u.GiteaCredentialsOutput != nil {
		return utils.MarshalJSON(u.GiteaCredentialsOutput, "", true)
	}

	if u.SSHCredentialsOutput != nil {
		return utils.MarshalJSON(u.SSHCredentialsOutput, "", true)
	}

	if u.KubernetesCredentialsOutput != nil {
		return utils.MarshalJSON(u.KubernetesCredentialsOutput, "", true)
	}

	if u.AzureCredentialsOutput != nil {
		return utils.MarshalJSON(u.AzureCredentialsOutput, "", true)
	}

	if u.AzureCloudCredentialsOutput != nil {
		return utils.MarshalJSON(u.AzureCloudCredentialsOutput, "", true)
	}

	if u.AzureReposCredentialsOutput != nil {
		return utils.MarshalJSON(u.AzureReposCredentialsOutput, "", true)
	}

	if u.ContainerRegistryCredentialsOutput != nil {
		return utils.MarshalJSON(u.ContainerRegistryCredentialsOutput, "", true)
	}

	if u.TowerAgentCredentials != nil {
		return utils.MarshalJSON(u.TowerAgentCredentials, "", true)
	}

	if u.AWSCodeCommitCredentialsOutput != nil {
		return utils.MarshalJSON(u.AWSCodeCommitCredentialsOutput, "", true)
	}

	if u.AzureEntraCredentialsOutput != nil {
		return utils.MarshalJSON(u.AzureEntraCredentialsOutput, "", true)
	}

	if u.SeqeraComputeCredentialsOutput != nil {
		return utils.MarshalJSON(u.SeqeraComputeCredentialsOutput, "", true)
	}

	if u.S3CompatibleCredentialsOutput != nil {
		return utils.MarshalJSON(u.S3CompatibleCredentialsOutput, "", true)
	}

	if u.LocalSecurityKeysOutput != nil {
		return utils.MarshalJSON(u.LocalSecurityKeysOutput, "", true)
	}

	return nil, errors.New("could not marshal union type SecurityKeysOutput: all fields are null")
}
