// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UserWorkspacePermissionDto struct {
	Permission *string  `json:"permission,omitempty"`
	Roles      []string `json:"roles,omitempty"`
}

func (u *UserWorkspacePermissionDto) GetPermission() *string {
	if u == nil {
		return nil
	}
	return u.Permission
}

func (u *UserWorkspacePermissionDto) GetRoles() []string {
	if u == nil {
		return nil
	}
	return u.Roles
}
