// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type WorkflowTypeVersion struct {
	WorkflowTypeVersion []string `json:"workflow_type_version,omitempty"`
}

func (w *WorkflowTypeVersion) GetWorkflowTypeVersion() []string {
	if w == nil {
		return nil
	}
	return w.WorkflowTypeVersion
}
