## Credentials
resource "seqera_azure_credential" "azure_credential" {
  name         = "azure_credential"
  workspace_id = var.workspace_id

  # Flattened Azure credential structure
  batch_key    = var.batch_key
  batch_name   = var.batch_name
  storage_key  = var.storage_key
  storage_name = var.storage_name
}

resource "seqera_compute_env" "azure_batch_compute_env" {
  workspace_id = var.workspace_id

  compute_env = {
    name           = "azure-batch-compute-env-terraform"
    description    = "azure Batch compute environment"
    platform       = "azure-batch"
    credentials_id = resource.seqera_azure_credential.azure_credential.credentials_id

    config = {
      azure_batch = {
        region   = "eastus"
        work_dir = var.work_dir
        #head_pool = "tower-pool-11OOCPR4OtcuwzdFSixWSu "
        forge = {
          vm_count = 1

        }
      }
    }
  }
}

resource "seqera_pipeline" "hello_world_minimal" {
  description = "Hello world pipeline generated by terraform"
  name        = "terraform-hello-world-azure"
  launch = {
    compute_env_id  = resource.seqera_compute_env.azure_batch_compute_env.compute_env_id
    config_profiles = []
    head_job_cpus   = 6
    # head_job_memory_mb = 32
    pipeline    = "https://github.com/nextflow-io/hello"
    pull_latest = true
    resume      = false
    revision    = "master"
    work_dir    = var.work_dir
  }
  workspace_id = var.workspace_id
}



## Launch a workflow
resource "seqera_workflows" "my_workflows" {
  compute_env_id = resource.seqera_compute_env.azure_batch_compute_env.compute_env_id
  pipeline       = "nextflow-io/hello"
  work_dir       = var.work_dir
  workspace_id   = var.workspace_id
  depends_on     = [seqera_compute_env.azure_batch_compute_env]
}
