// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/operations"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
)

// AWSCredentialResourceModelOptions enables patch sdk method construction.
type AWSCredentialResourceModelOptions struct {
	Config *AWSCredentialResourceModel
	State  *AWSCredentialResourceModel
}

func (r *AWSCredentialResourceModel) RefreshFromSharedAWSCredentialKeysOutput(ctx context.Context, resp *shared.AWSCredentialKeysOutput) diag.Diagnostics {
	var diags diag.Diagnostics

	r.AccessKey = types.StringPointerValue(resp.AccessKey)
	r.ExternalID = types.StringPointerValue(resp.ExternalID)
	if resp.Mode != nil {
		r.Mode = types.StringValue(string(*resp.Mode))
	} else {
		r.Mode = types.StringNull()
	}

	return diags
}

func (r *AWSCredentialResourceModel) RefreshFromSharedAWSCredentialOutput(ctx context.Context, resp *shared.AWSCredentialOutput) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CredentialsID = types.StringPointerValue(resp.CredentialsID)
		diags.Append(r.RefreshFromSharedAWSCredentialKeysOutput(ctx, &resp.Keys)...)

		if diags.HasError() {
			return diags
		}

		r.Name = types.StringValue(resp.Name)
		if resp.ProviderType != nil {
			r.ProviderType = types.StringValue(string(*resp.ProviderType))
		} else {
			r.ProviderType = types.StringNull()
		}
	}

	return diags
}

func (r *AWSCredentialResourceModel) RefreshFromSharedCreateAWSCredentialsResponse(ctx context.Context, resp *shared.CreateAWSCredentialsResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CredentialsID = types.StringPointerValue(resp.CredentialsID)
	}

	return diags
}

func (r *AWSCredentialResourceModel) RefreshFromSharedDescribeAWSCredentialsResponse(ctx context.Context, resp *shared.DescribeAWSCredentialsResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedAWSCredentialOutput(ctx, resp.Credentials)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *AWSCredentialResourceModel) ToOperationsCreateAWSCredentialsRequest(ctx context.Context, opts *AWSCredentialResourceModelOptions) (*operations.CreateAWSCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	useExternalID := new(bool)
	if !r.UseExternalID.IsUnknown() && !r.UseExternalID.IsNull() {
		*useExternalID = r.UseExternalID.ValueBool()
	} else {
		useExternalID = nil
	}
	createAWSCredentialsRequest, createAWSCredentialsRequestDiags := r.ToSharedCreateAWSCredentialsRequest(ctx, opts)
	diags.Append(createAWSCredentialsRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreateAWSCredentialsRequest{
		WorkspaceID:                 workspaceID,
		UseExternalID:               useExternalID,
		CreateAWSCredentialsRequest: *createAWSCredentialsRequest,
	}

	return &out, diags
}

func (r *AWSCredentialResourceModel) ToOperationsDeleteAWSCredentialsRequest(ctx context.Context, opts *AWSCredentialResourceModelOptions) (*operations.DeleteAWSCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var credentialsID string
	credentialsID = r.CredentialsID.ValueString()

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	out := operations.DeleteAWSCredentialsRequest{
		CredentialsID: credentialsID,
		WorkspaceID:   workspaceID,
	}

	return &out, diags
}

func (r *AWSCredentialResourceModel) ToOperationsDescribeAWSCredentialsRequest(ctx context.Context, opts *AWSCredentialResourceModelOptions) (*operations.DescribeAWSCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var credentialsID string
	credentialsID = r.CredentialsID.ValueString()

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	out := operations.DescribeAWSCredentialsRequest{
		CredentialsID: credentialsID,
		WorkspaceID:   workspaceID,
	}

	return &out, diags
}

func (r *AWSCredentialResourceModel) ToOperationsUpdateAWSCredentialsRequest(ctx context.Context, opts *AWSCredentialResourceModelOptions) (*operations.UpdateAWSCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var credentialsID string
	credentialsID = r.CredentialsID.ValueString()

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	useExternalID := new(bool)
	if !r.UseExternalID.IsUnknown() && !r.UseExternalID.IsNull() {
		*useExternalID = r.UseExternalID.ValueBool()
	} else {
		useExternalID = nil
	}
	updateAWSCredentialsRequest, updateAWSCredentialsRequestDiags := r.ToSharedUpdateAWSCredentialsRequest(ctx, opts)
	diags.Append(updateAWSCredentialsRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateAWSCredentialsRequest{
		CredentialsID:               credentialsID,
		WorkspaceID:                 workspaceID,
		UseExternalID:               useExternalID,
		UpdateAWSCredentialsRequest: *updateAWSCredentialsRequest,
	}

	return &out, diags
}

func (r *AWSCredentialResourceModel) ToSharedAWSCredential(ctx context.Context, opts *AWSCredentialResourceModelOptions) (*shared.AWSCredential, diag.Diagnostics) {
	var diags diag.Diagnostics

	credentialsID := new(string)
	if !r.CredentialsID.IsUnknown() && !r.CredentialsID.IsNull() {
		*credentialsID = r.CredentialsID.ValueString()
	} else {
		credentialsID = nil
	}
	var name string
	name = r.Name.ValueString()

	providerType := new(shared.AWSCredentialProviderType)
	if !r.ProviderType.IsUnknown() && !r.ProviderType.IsNull() {
		*providerType = shared.AWSCredentialProviderType(r.ProviderType.ValueString())
	} else {
		providerType = nil
	}
	keys, keysDiags := r.ToSharedAWSCredentialKeys(ctx, opts)
	diags.Append(keysDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := shared.AWSCredential{
		CredentialsID: credentialsID,
		Name:          name,
		ProviderType:  providerType,
		Keys:          *keys,
	}

	return &out, diags
}

func (r *AWSCredentialResourceModel) ToSharedAWSCredentialKeys(ctx context.Context, opts *AWSCredentialResourceModelOptions) (*shared.AWSCredentialKeys, diag.Diagnostics) {
	var diags diag.Diagnostics

	accessKey := new(string)
	if !r.AccessKey.IsUnknown() && !r.AccessKey.IsNull() {
		*accessKey = r.AccessKey.ValueString()
	} else {
		accessKey = nil
	}
	secretKey := new(string)
	if !opts.Config.SecretKey.IsUnknown() && !opts.Config.SecretKey.IsNull() {
		*secretKey = opts.Config.SecretKey.ValueString()
	} else {
		secretKey = nil
	}
	assumeRoleArn := new(string)
	if !r.AssumeRoleArn.IsUnknown() && !r.AssumeRoleArn.IsNull() {
		*assumeRoleArn = r.AssumeRoleArn.ValueString()
	} else {
		assumeRoleArn = nil
	}
	mode := new(shared.AwsCredentialsMode)
	if !r.Mode.IsUnknown() && !r.Mode.IsNull() {
		*mode = shared.AwsCredentialsMode(r.Mode.ValueString())
	} else {
		mode = nil
	}
	externalID := new(string)
	if !r.ExternalID.IsUnknown() && !r.ExternalID.IsNull() {
		*externalID = r.ExternalID.ValueString()
	} else {
		externalID = nil
	}
	out := shared.AWSCredentialKeys{
		AccessKey:     accessKey,
		SecretKey:     secretKey,
		AssumeRoleArn: assumeRoleArn,
		Mode:          mode,
		ExternalID:    externalID,
	}

	return &out, diags
}

func (r *AWSCredentialResourceModel) ToSharedCreateAWSCredentialsRequest(ctx context.Context, opts *AWSCredentialResourceModelOptions) (*shared.CreateAWSCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	credentials, credentialsDiags := r.ToSharedAWSCredential(ctx, opts)
	diags.Append(credentialsDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := shared.CreateAWSCredentialsRequest{
		Credentials: credentials,
	}

	return &out, diags
}

func (r *AWSCredentialResourceModel) ToSharedUpdateAWSCredentialsRequest(ctx context.Context, opts *AWSCredentialResourceModelOptions) (*shared.UpdateAWSCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	credentials, credentialsDiags := r.ToSharedAWSCredential(ctx, opts)
	diags.Append(credentialsDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := shared.UpdateAWSCredentialsRequest{
		Credentials: credentials,
	}

	return &out, diags
}
