// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/operations"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
)

// GoogleCredentialResourceModelOptions enables patch sdk method construction.
type GoogleCredentialResourceModelOptions struct {
	Config *GoogleCredentialResourceModel
	State  *GoogleCredentialResourceModel
}

func (r *GoogleCredentialResourceModel) RefreshFromSharedCreateGoogleCredentialsResponse(ctx context.Context, resp *shared.CreateGoogleCredentialsResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CredentialsID = types.StringPointerValue(resp.CredentialsID)
	}

	return diags
}

func (r *GoogleCredentialResourceModel) RefreshFromSharedDescribeGoogleCredentialsResponse(ctx context.Context, resp *shared.DescribeGoogleCredentialsResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedGoogleCredentialOutput(ctx, resp.Credentials)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *GoogleCredentialResourceModel) RefreshFromSharedGoogleCredentialKeysOutput(ctx context.Context, resp *shared.GoogleCredentialKeysOutput) diag.Diagnostics {
	var diags diag.Diagnostics

	r.ServiceAccountEmail = types.StringPointerValue(resp.ServiceAccountEmail)
	r.TokenAudience = types.StringPointerValue(resp.TokenAudience)
	r.WorkloadIdentityProvider = types.StringPointerValue(resp.WorkloadIdentityProvider)

	return diags
}

func (r *GoogleCredentialResourceModel) RefreshFromSharedGoogleCredentialOutput(ctx context.Context, resp *shared.GoogleCredentialOutput) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CredentialsID = types.StringPointerValue(resp.CredentialsID)
		diags.Append(r.RefreshFromSharedGoogleCredentialKeysOutput(ctx, &resp.Keys)...)

		if diags.HasError() {
			return diags
		}

		r.Name = types.StringValue(resp.Name)
		if resp.ProviderType != nil {
			r.ProviderType = types.StringValue(string(*resp.ProviderType))
		} else {
			r.ProviderType = types.StringNull()
		}
	}

	return diags
}

func (r *GoogleCredentialResourceModel) ToOperationsCreateGoogleCredentialsRequest(ctx context.Context, opts *GoogleCredentialResourceModelOptions) (*operations.CreateGoogleCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	createGoogleCredentialsRequest, createGoogleCredentialsRequestDiags := r.ToSharedCreateGoogleCredentialsRequest(ctx, opts)
	diags.Append(createGoogleCredentialsRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreateGoogleCredentialsRequest{
		WorkspaceID:                    workspaceID,
		CreateGoogleCredentialsRequest: *createGoogleCredentialsRequest,
	}

	return &out, diags
}

func (r *GoogleCredentialResourceModel) ToOperationsDeleteGoogleCredentialsRequest(ctx context.Context, opts *GoogleCredentialResourceModelOptions) (*operations.DeleteGoogleCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var credentialsID string
	credentialsID = r.CredentialsID.ValueString()

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	out := operations.DeleteGoogleCredentialsRequest{
		CredentialsID: credentialsID,
		WorkspaceID:   workspaceID,
	}

	return &out, diags
}

func (r *GoogleCredentialResourceModel) ToOperationsDescribeGoogleCredentialsRequest(ctx context.Context, opts *GoogleCredentialResourceModelOptions) (*operations.DescribeGoogleCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var credentialsID string
	credentialsID = r.CredentialsID.ValueString()

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	out := operations.DescribeGoogleCredentialsRequest{
		CredentialsID: credentialsID,
		WorkspaceID:   workspaceID,
	}

	return &out, diags
}

func (r *GoogleCredentialResourceModel) ToOperationsUpdateGoogleCredentialsRequest(ctx context.Context, opts *GoogleCredentialResourceModelOptions) (*operations.UpdateGoogleCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var credentialsID string
	credentialsID = r.CredentialsID.ValueString()

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	updateGoogleCredentialsRequest, updateGoogleCredentialsRequestDiags := r.ToSharedUpdateGoogleCredentialsRequest(ctx, opts)
	diags.Append(updateGoogleCredentialsRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateGoogleCredentialsRequest{
		CredentialsID:                  credentialsID,
		WorkspaceID:                    workspaceID,
		UpdateGoogleCredentialsRequest: *updateGoogleCredentialsRequest,
	}

	return &out, diags
}

func (r *GoogleCredentialResourceModel) ToSharedCreateGoogleCredentialsRequest(ctx context.Context, opts *GoogleCredentialResourceModelOptions) (*shared.CreateGoogleCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	credentials, credentialsDiags := r.ToSharedGoogleCredential(ctx, opts)
	diags.Append(credentialsDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := shared.CreateGoogleCredentialsRequest{
		Credentials: *credentials,
	}

	return &out, diags
}

func (r *GoogleCredentialResourceModel) ToSharedGoogleCredential(ctx context.Context, opts *GoogleCredentialResourceModelOptions) (*shared.GoogleCredential, diag.Diagnostics) {
	var diags diag.Diagnostics

	credentialsID := new(string)
	if !r.CredentialsID.IsUnknown() && !r.CredentialsID.IsNull() {
		*credentialsID = r.CredentialsID.ValueString()
	} else {
		credentialsID = nil
	}
	var name string
	name = r.Name.ValueString()

	providerType := new(shared.GoogleCredentialProviderType)
	if !r.ProviderType.IsUnknown() && !r.ProviderType.IsNull() {
		*providerType = shared.GoogleCredentialProviderType(r.ProviderType.ValueString())
	} else {
		providerType = nil
	}
	keys, keysDiags := r.ToSharedGoogleCredentialKeys(ctx, opts)
	diags.Append(keysDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := shared.GoogleCredential{
		CredentialsID: credentialsID,
		Name:          name,
		ProviderType:  providerType,
		Keys:          *keys,
	}

	return &out, diags
}

func (r *GoogleCredentialResourceModel) ToSharedGoogleCredentialKeys(ctx context.Context, opts *GoogleCredentialResourceModelOptions) (*shared.GoogleCredentialKeys, diag.Diagnostics) {
	var diags diag.Diagnostics

	data := new(string)
	if !opts.Config.Data.IsUnknown() && !opts.Config.Data.IsNull() {
		*data = opts.Config.Data.ValueString()
	} else {
		data = nil
	}
	workloadIdentityProvider := new(string)
	if !r.WorkloadIdentityProvider.IsUnknown() && !r.WorkloadIdentityProvider.IsNull() {
		*workloadIdentityProvider = r.WorkloadIdentityProvider.ValueString()
	} else {
		workloadIdentityProvider = nil
	}
	serviceAccountEmail := new(string)
	if !r.ServiceAccountEmail.IsUnknown() && !r.ServiceAccountEmail.IsNull() {
		*serviceAccountEmail = r.ServiceAccountEmail.ValueString()
	} else {
		serviceAccountEmail = nil
	}
	tokenAudience := new(string)
	if !r.TokenAudience.IsUnknown() && !r.TokenAudience.IsNull() {
		*tokenAudience = r.TokenAudience.ValueString()
	} else {
		tokenAudience = nil
	}
	out := shared.GoogleCredentialKeys{
		Data:                     data,
		WorkloadIdentityProvider: workloadIdentityProvider,
		ServiceAccountEmail:      serviceAccountEmail,
		TokenAudience:            tokenAudience,
	}

	return &out, diags
}

func (r *GoogleCredentialResourceModel) ToSharedUpdateGoogleCredentialsRequest(ctx context.Context, opts *GoogleCredentialResourceModelOptions) (*shared.UpdateGoogleCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	credentials, credentialsDiags := r.ToSharedGoogleCredential(ctx, opts)
	diags.Append(credentialsDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := shared.UpdateGoogleCredentialsRequest{
		Credentials: *credentials,
	}

	return &out, diags
}
