// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/seqeralabs/terraform-provider-seqera/internal/provider/typeconvert"
	tfTypes "github.com/seqeralabs/terraform-provider-seqera/internal/provider/types"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/operations"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"time"
)

func (r *ManagedComputeCEResourceModel) RefreshFromSharedConfig(ctx context.Context, resp *shared.Config) diag.Diagnostics {
	var diags diag.Diagnostics

	r.DataRetentionPolicy = types.BoolPointerValue(resp.DataRetentionPolicy)
	r.Environment = []tfTypes.ConfigEnvVariable{}

	for _, environmentItem := range resp.Environment {
		var environment tfTypes.ConfigEnvVariable

		environment.Compute = types.BoolPointerValue(environmentItem.Compute)
		environment.Head = types.BoolPointerValue(environmentItem.Head)
		environment.Name = types.StringPointerValue(environmentItem.Name)
		environment.Value = types.StringPointerValue(environmentItem.Value)

		r.Environment = append(r.Environment, environment)
	}
	if resp.InstanceSize != nil {
		r.InstanceSize = types.StringValue(string(*resp.InstanceSize))
	} else {
		r.InstanceSize = types.StringNull()
	}
	r.NextflowConfig = types.StringPointerValue(resp.NextflowConfig)
	r.PostRunScript = types.StringPointerValue(resp.PostRunScript)
	r.PreRunScript = types.StringPointerValue(resp.PreRunScript)
	r.Region = types.StringPointerValue(resp.Region)
	r.ResourceLabelIds = make([]types.Int64, 0, len(resp.ResourceLabelIds))
	for _, v := range resp.ResourceLabelIds {
		r.ResourceLabelIds = append(r.ResourceLabelIds, types.Int64Value(v))
	}
	r.WorkDir = types.StringPointerValue(resp.WorkDir)

	return diags
}

func (r *ManagedComputeCEResourceModel) RefreshFromSharedCreateManagedComputeCEResponse(ctx context.Context, resp *shared.CreateManagedComputeCEResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.ComputeEnvID = types.StringPointerValue(resp.ComputeEnvID)
	}

	return diags
}

func (r *ManagedComputeCEResourceModel) RefreshFromSharedDescribeManagedComputeCEResponse(ctx context.Context, resp *shared.DescribeManagedComputeCEResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedManagedComputeCEComputeConfig(ctx, resp.ComputeEnv)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *ManagedComputeCEResourceModel) RefreshFromSharedManagedComputeCEComputeConfig(ctx context.Context, resp *shared.ManagedComputeCEComputeConfig) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedConfig(ctx, &resp.Config)...)

		if diags.HasError() {
			return diags
		}

		r.DateCreated = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.DateCreated))
		r.Deleted = types.BoolPointerValue(resp.Deleted)
		r.ID = types.StringPointerValue(resp.ID)
		r.LastUpdated = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.LastUpdated))
		r.LastUsed = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.LastUsed))
		r.Name = types.StringValue(resp.Name)
		r.OrgID = types.Int64PointerValue(resp.OrgID)
		if resp.Platform != nil {
			r.Platform = types.StringValue(string(*resp.Platform))
		} else {
			r.Platform = types.StringNull()
		}
		r.Status = types.StringPointerValue(resp.Status)
		r.WorkspaceID = types.Int64PointerValue(resp.WorkspaceID)
	}

	return diags
}

func (r *ManagedComputeCEResourceModel) ToOperationsCreateManagedComputeCERequest(ctx context.Context) (*operations.CreateManagedComputeCERequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var workspaceID int64
	workspaceID = r.WorkspaceID.ValueInt64()

	createManagedComputeCERequest, createManagedComputeCERequestDiags := r.ToSharedCreateManagedComputeCERequest(ctx)
	diags.Append(createManagedComputeCERequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreateManagedComputeCERequest{
		WorkspaceID:                   workspaceID,
		CreateManagedComputeCERequest: *createManagedComputeCERequest,
	}

	return &out, diags
}

func (r *ManagedComputeCEResourceModel) ToOperationsDeleteManagedComputeCERequest(ctx context.Context) (*operations.DeleteManagedComputeCERequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var computeEnvID string
	computeEnvID = r.ComputeEnvID.ValueString()

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	out := operations.DeleteManagedComputeCERequest{
		ComputeEnvID: computeEnvID,
		WorkspaceID:  workspaceID,
	}

	return &out, diags
}

func (r *ManagedComputeCEResourceModel) ToOperationsDescribeManagedComputeCERequest(ctx context.Context) (*operations.DescribeManagedComputeCERequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var computeEnvID string
	computeEnvID = r.ComputeEnvID.ValueString()

	var workspaceID int64
	workspaceID = r.WorkspaceID.ValueInt64()

	out := operations.DescribeManagedComputeCERequest{
		ComputeEnvID: computeEnvID,
		WorkspaceID:  workspaceID,
	}

	return &out, diags
}

func (r *ManagedComputeCEResourceModel) ToSharedConfig(ctx context.Context) (*shared.Config, diag.Diagnostics) {
	var diags diag.Diagnostics

	region := new(string)
	if !r.Region.IsUnknown() && !r.Region.IsNull() {
		*region = r.Region.ValueString()
	} else {
		region = nil
	}
	instanceSize := new(shared.InstanceSize)
	if !r.InstanceSize.IsUnknown() && !r.InstanceSize.IsNull() {
		*instanceSize = shared.InstanceSize(r.InstanceSize.ValueString())
	} else {
		instanceSize = nil
	}
	workDir := new(string)
	if !r.WorkDir.IsUnknown() && !r.WorkDir.IsNull() {
		*workDir = r.WorkDir.ValueString()
	} else {
		workDir = nil
	}
	dataRetentionPolicy := new(bool)
	if !r.DataRetentionPolicy.IsUnknown() && !r.DataRetentionPolicy.IsNull() {
		*dataRetentionPolicy = r.DataRetentionPolicy.ValueBool()
	} else {
		dataRetentionPolicy = nil
	}
	resourceLabelIds := make([]int64, 0, len(r.ResourceLabelIds))
	for resourceLabelIdsIndex := range r.ResourceLabelIds {
		resourceLabelIds = append(resourceLabelIds, r.ResourceLabelIds[resourceLabelIdsIndex].ValueInt64())
	}
	preRunScript := new(string)
	if !r.PreRunScript.IsUnknown() && !r.PreRunScript.IsNull() {
		*preRunScript = r.PreRunScript.ValueString()
	} else {
		preRunScript = nil
	}
	postRunScript := new(string)
	if !r.PostRunScript.IsUnknown() && !r.PostRunScript.IsNull() {
		*postRunScript = r.PostRunScript.ValueString()
	} else {
		postRunScript = nil
	}
	nextflowConfig := new(string)
	if !r.NextflowConfig.IsUnknown() && !r.NextflowConfig.IsNull() {
		*nextflowConfig = r.NextflowConfig.ValueString()
	} else {
		nextflowConfig = nil
	}
	environment := make([]shared.ConfigEnvVariable, 0, len(r.Environment))
	for environmentIndex := range r.Environment {
		compute := new(bool)
		if !r.Environment[environmentIndex].Compute.IsUnknown() && !r.Environment[environmentIndex].Compute.IsNull() {
			*compute = r.Environment[environmentIndex].Compute.ValueBool()
		} else {
			compute = nil
		}
		head := new(bool)
		if !r.Environment[environmentIndex].Head.IsUnknown() && !r.Environment[environmentIndex].Head.IsNull() {
			*head = r.Environment[environmentIndex].Head.ValueBool()
		} else {
			head = nil
		}
		name := new(string)
		if !r.Environment[environmentIndex].Name.IsUnknown() && !r.Environment[environmentIndex].Name.IsNull() {
			*name = r.Environment[environmentIndex].Name.ValueString()
		} else {
			name = nil
		}
		value := new(string)
		if !r.Environment[environmentIndex].Value.IsUnknown() && !r.Environment[environmentIndex].Value.IsNull() {
			*value = r.Environment[environmentIndex].Value.ValueString()
		} else {
			value = nil
		}
		environment = append(environment, shared.ConfigEnvVariable{
			Compute: compute,
			Head:    head,
			Name:    name,
			Value:   value,
		})
	}
	out := shared.Config{
		Region:              region,
		InstanceSize:        instanceSize,
		WorkDir:             workDir,
		DataRetentionPolicy: dataRetentionPolicy,
		ResourceLabelIds:    resourceLabelIds,
		PreRunScript:        preRunScript,
		PostRunScript:       postRunScript,
		NextflowConfig:      nextflowConfig,
		Environment:         environment,
	}

	return &out, diags
}

func (r *ManagedComputeCEResourceModel) ToSharedCreateManagedComputeCERequest(ctx context.Context) (*shared.CreateManagedComputeCERequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	computeEnv, computeEnvDiags := r.ToSharedManagedComputeCEComputeConfigInput(ctx)
	diags.Append(computeEnvDiags...)

	if diags.HasError() {
		return nil, diags
	}

	labelIds := make([]int64, 0, len(r.LabelIds))
	for labelIdsIndex := range r.LabelIds {
		labelIds = append(labelIds, r.LabelIds[labelIdsIndex].ValueInt64())
	}
	out := shared.CreateManagedComputeCERequest{
		ComputeEnv: computeEnv,
		LabelIds:   labelIds,
	}

	return &out, diags
}

func (r *ManagedComputeCEResourceModel) ToSharedManagedComputeCEComputeConfigInput(ctx context.Context) (*shared.ManagedComputeCEComputeConfigInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	id := new(string)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueString()
	} else {
		id = nil
	}
	var name string
	name = r.Name.ValueString()

	platform := new(shared.ManagedComputeCEComputeConfigPlatform)
	if !r.Platform.IsUnknown() && !r.Platform.IsNull() {
		*platform = shared.ManagedComputeCEComputeConfigPlatform(r.Platform.ValueString())
	} else {
		platform = nil
	}
	status := new(string)
	if !r.Status.IsUnknown() && !r.Status.IsNull() {
		*status = r.Status.ValueString()
	} else {
		status = nil
	}
	dateCreated := new(time.Time)
	if !r.DateCreated.IsUnknown() && !r.DateCreated.IsNull() {
		*dateCreated, _ = time.Parse(time.RFC3339Nano, r.DateCreated.ValueString())
	} else {
		dateCreated = nil
	}
	lastUpdated := new(time.Time)
	if !r.LastUpdated.IsUnknown() && !r.LastUpdated.IsNull() {
		*lastUpdated, _ = time.Parse(time.RFC3339Nano, r.LastUpdated.ValueString())
	} else {
		lastUpdated = nil
	}
	lastUsed := new(time.Time)
	if !r.LastUsed.IsUnknown() && !r.LastUsed.IsNull() {
		*lastUsed, _ = time.Parse(time.RFC3339Nano, r.LastUsed.ValueString())
	} else {
		lastUsed = nil
	}
	deleted := new(bool)
	if !r.Deleted.IsUnknown() && !r.Deleted.IsNull() {
		*deleted = r.Deleted.ValueBool()
	} else {
		deleted = nil
	}
	config, configDiags := r.ToSharedConfig(ctx)
	diags.Append(configDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := shared.ManagedComputeCEComputeConfigInput{
		WorkspaceID: workspaceID,
		ID:          id,
		Name:        name,
		Platform:    platform,
		Status:      status,
		DateCreated: dateCreated,
		LastUpdated: lastUpdated,
		LastUsed:    lastUsed,
		Deleted:     deleted,
		Config:      *config,
	}

	return &out, diags
}
