// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/seqeralabs/terraform-provider-seqera/internal/provider/typeconvert"
	tfTypes "github.com/seqeralabs/terraform-provider-seqera/internal/provider/types"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/operations"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
)

func (r *PipelineResourceModel) RefreshFromSharedCreatePipelineResponse(ctx context.Context, resp *shared.CreatePipelineResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedPipelineDbDto(ctx, resp.Pipeline)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *PipelineResourceModel) RefreshFromSharedDescribePipelineResponse(ctx context.Context, resp *shared.DescribePipelineResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedPipelineDbDto(ctx, resp.Pipeline)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *PipelineResourceModel) RefreshFromSharedPipelineDbDto(ctx context.Context, resp *shared.PipelineDbDto) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Description = types.StringPointerValue(resp.Description)
		r.Icon = types.StringPointerValue(resp.Icon)
		r.Name = types.StringPointerValue(resp.Name)
		r.PipelineID = types.Int64PointerValue(resp.PipelineID)
		r.Repository = types.StringPointerValue(resp.Repository)
		r.UserFirstName = types.StringPointerValue(resp.UserFirstName)
		r.UserID = types.Int64PointerValue(resp.UserID)
		r.UserName = types.StringPointerValue(resp.UserName)
		if resp.Version == nil {
			r.Version = nil
		} else {
			r.Version = &tfTypes.CreatePipelineVersionRequest{}
			r.Version.CreatorAvatarURL = types.StringPointerValue(resp.Version.CreatorAvatarURL)
			r.Version.CreatorFirstName = types.StringPointerValue(resp.Version.CreatorFirstName)
			r.Version.CreatorLastName = types.StringPointerValue(resp.Version.CreatorLastName)
			r.Version.CreatorUserID = types.Int64PointerValue(resp.Version.CreatorUserID)
			r.Version.CreatorUserName = types.StringPointerValue(resp.Version.CreatorUserName)
			r.Version.DateCreated = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.Version.DateCreated))
			r.Version.Hash = types.StringPointerValue(resp.Version.Hash)
			r.Version.ID = types.StringPointerValue(resp.Version.ID)
			r.Version.IsDefault = types.BoolPointerValue(resp.Version.IsDefault)
			r.Version.LastUpdated = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.Version.LastUpdated))
			r.Version.Name = types.StringPointerValue(resp.Version.Name)
		}
		r.WorkspaceID = types.Int64PointerValue(resp.WorkspaceID)
	}

	return diags
}

func (r *PipelineResourceModel) RefreshFromSharedUpdatePipelineResponse(ctx context.Context, resp *shared.UpdatePipelineResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedPipelineDbDto(ctx, resp.Pipeline)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *PipelineResourceModel) ToOperationsCreatePipelineRequest(ctx context.Context) (*operations.CreatePipelineRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	createPipelineRequest, createPipelineRequestDiags := r.ToSharedCreatePipelineRequest(ctx)
	diags.Append(createPipelineRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreatePipelineRequest{
		WorkspaceID:           workspaceID,
		CreatePipelineRequest: *createPipelineRequest,
	}

	return &out, diags
}

func (r *PipelineResourceModel) ToOperationsDeletePipelineRequest(ctx context.Context) (*operations.DeletePipelineRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var pipelineID int64
	pipelineID = r.PipelineID.ValueInt64()

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	out := operations.DeletePipelineRequest{
		PipelineID:  pipelineID,
		WorkspaceID: workspaceID,
	}

	return &out, diags
}

func (r *PipelineResourceModel) ToOperationsDescribePipelineRequest(ctx context.Context) (*operations.DescribePipelineRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var pipelineID int64
	pipelineID = r.PipelineID.ValueInt64()

	var workspaceID int64
	workspaceID = r.WorkspaceID.ValueInt64()

	out := operations.DescribePipelineRequest{
		PipelineID:  pipelineID,
		WorkspaceID: workspaceID,
	}

	return &out, diags
}

func (r *PipelineResourceModel) ToOperationsUpdatePipelineRequest(ctx context.Context) (*operations.UpdatePipelineRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var pipelineID int64
	pipelineID = r.PipelineID.ValueInt64()

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	updatePipelineRequest, updatePipelineRequestDiags := r.ToSharedUpdatePipelineRequest(ctx)
	diags.Append(updatePipelineRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdatePipelineRequest{
		PipelineID:            pipelineID,
		WorkspaceID:           workspaceID,
		UpdatePipelineRequest: *updatePipelineRequest,
	}

	return &out, diags
}

func (r *PipelineResourceModel) ToSharedCreatePipelineRequest(ctx context.Context) (*shared.CreatePipelineRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	icon := new(string)
	if !r.Icon.IsUnknown() && !r.Icon.IsNull() {
		*icon = r.Icon.ValueString()
	} else {
		icon = nil
	}
	labelIds := make([]int64, 0, len(r.LabelIds))
	for labelIdsIndex := range r.LabelIds {
		labelIds = append(labelIds, r.LabelIds[labelIdsIndex].ValueInt64())
	}
	computeEnvID := new(string)
	if !r.Launch.ComputeEnvID.IsUnknown() && !r.Launch.ComputeEnvID.IsNull() {
		*computeEnvID = r.Launch.ComputeEnvID.ValueString()
	} else {
		computeEnvID = nil
	}
	configProfiles := make([]string, 0, len(r.Launch.ConfigProfiles))
	for configProfilesIndex := range r.Launch.ConfigProfiles {
		configProfiles = append(configProfiles, r.Launch.ConfigProfiles[configProfilesIndex].ValueString())
	}
	configText := new(string)
	if !r.Launch.ConfigText.IsUnknown() && !r.Launch.ConfigText.IsNull() {
		*configText = r.Launch.ConfigText.ValueString()
	} else {
		configText = nil
	}
	entryName := new(string)
	if !r.Launch.EntryName.IsUnknown() && !r.Launch.EntryName.IsNull() {
		*entryName = r.Launch.EntryName.ValueString()
	} else {
		entryName = nil
	}
	headJobCpus := new(int)
	if !r.Launch.HeadJobCpus.IsUnknown() && !r.Launch.HeadJobCpus.IsNull() {
		*headJobCpus = int(r.Launch.HeadJobCpus.ValueInt32())
	} else {
		headJobCpus = nil
	}
	headJobMemoryMb := new(int)
	if !r.Launch.HeadJobMemoryMb.IsUnknown() && !r.Launch.HeadJobMemoryMb.IsNull() {
		*headJobMemoryMb = int(r.Launch.HeadJobMemoryMb.ValueInt32())
	} else {
		headJobMemoryMb = nil
	}
	labelIds1 := make([]int64, 0, len(r.Launch.LabelIds))
	for labelIdsIndex1 := range r.Launch.LabelIds {
		labelIds1 = append(labelIds1, r.Launch.LabelIds[labelIdsIndex1].ValueInt64())
	}
	mainScript := new(string)
	if !r.Launch.MainScript.IsUnknown() && !r.Launch.MainScript.IsNull() {
		*mainScript = r.Launch.MainScript.ValueString()
	} else {
		mainScript = nil
	}
	paramsText := new(string)
	if !r.Launch.ParamsText.IsUnknown() && !r.Launch.ParamsText.IsNull() {
		*paramsText = r.Launch.ParamsText.ValueString()
	} else {
		paramsText = nil
	}
	pipeline := new(string)
	if !r.Launch.Pipeline.IsUnknown() && !r.Launch.Pipeline.IsNull() {
		*pipeline = r.Launch.Pipeline.ValueString()
	} else {
		pipeline = nil
	}
	pipelineSchemaID := new(int64)
	if !r.Launch.PipelineSchemaID.IsUnknown() && !r.Launch.PipelineSchemaID.IsNull() {
		*pipelineSchemaID = r.Launch.PipelineSchemaID.ValueInt64()
	} else {
		pipelineSchemaID = nil
	}
	postRunScript := new(string)
	if !r.Launch.PostRunScript.IsUnknown() && !r.Launch.PostRunScript.IsNull() {
		*postRunScript = r.Launch.PostRunScript.ValueString()
	} else {
		postRunScript = nil
	}
	preRunScript := new(string)
	if !r.Launch.PreRunScript.IsUnknown() && !r.Launch.PreRunScript.IsNull() {
		*preRunScript = r.Launch.PreRunScript.ValueString()
	} else {
		preRunScript = nil
	}
	pullLatest := new(bool)
	if !r.Launch.PullLatest.IsUnknown() && !r.Launch.PullLatest.IsNull() {
		*pullLatest = r.Launch.PullLatest.ValueBool()
	} else {
		pullLatest = nil
	}
	resume := new(bool)
	if !r.Launch.Resume.IsUnknown() && !r.Launch.Resume.IsNull() {
		*resume = r.Launch.Resume.ValueBool()
	} else {
		resume = nil
	}
	revision := new(string)
	if !r.Launch.Revision.IsUnknown() && !r.Launch.Revision.IsNull() {
		*revision = r.Launch.Revision.ValueString()
	} else {
		revision = nil
	}
	runName := new(string)
	if !r.Launch.RunName.IsUnknown() && !r.Launch.RunName.IsNull() {
		*runName = r.Launch.RunName.ValueString()
	} else {
		runName = nil
	}
	schemaName := new(string)
	if !r.Launch.SchemaName.IsUnknown() && !r.Launch.SchemaName.IsNull() {
		*schemaName = r.Launch.SchemaName.ValueString()
	} else {
		schemaName = nil
	}
	stubRun := new(bool)
	if !r.Launch.StubRun.IsUnknown() && !r.Launch.StubRun.IsNull() {
		*stubRun = r.Launch.StubRun.ValueBool()
	} else {
		stubRun = nil
	}
	towerConfig := new(string)
	if !r.Launch.TowerConfig.IsUnknown() && !r.Launch.TowerConfig.IsNull() {
		*towerConfig = r.Launch.TowerConfig.ValueString()
	} else {
		towerConfig = nil
	}
	userSecrets := make([]string, 0, len(r.Launch.UserSecrets))
	for userSecretsIndex := range r.Launch.UserSecrets {
		userSecrets = append(userSecrets, r.Launch.UserSecrets[userSecretsIndex].ValueString())
	}
	workDir := new(string)
	if !r.Launch.WorkDir.IsUnknown() && !r.Launch.WorkDir.IsNull() {
		*workDir = r.Launch.WorkDir.ValueString()
	} else {
		workDir = nil
	}
	workspaceSecrets := make([]string, 0, len(r.Launch.WorkspaceSecrets))
	for workspaceSecretsIndex := range r.Launch.WorkspaceSecrets {
		workspaceSecrets = append(workspaceSecrets, r.Launch.WorkspaceSecrets[workspaceSecretsIndex].ValueString())
	}
	launch := shared.WorkflowLaunchRequest{
		ComputeEnvID:     computeEnvID,
		ConfigProfiles:   configProfiles,
		ConfigText:       configText,
		EntryName:        entryName,
		HeadJobCpus:      headJobCpus,
		HeadJobMemoryMb:  headJobMemoryMb,
		LabelIds:         labelIds1,
		MainScript:       mainScript,
		ParamsText:       paramsText,
		Pipeline:         pipeline,
		PipelineSchemaID: pipelineSchemaID,
		PostRunScript:    postRunScript,
		PreRunScript:     preRunScript,
		PullLatest:       pullLatest,
		Resume:           resume,
		Revision:         revision,
		RunName:          runName,
		SchemaName:       schemaName,
		StubRun:          stubRun,
		TowerConfig:      towerConfig,
		UserSecrets:      userSecrets,
		WorkDir:          workDir,
		WorkspaceSecrets: workspaceSecrets,
	}
	var name string
	name = r.Name.ValueString()

	var version *shared.CreatePipelineVersionRequest
	if r.Version != nil {
		name1 := new(string)
		if !r.Version.Name.IsUnknown() && !r.Version.Name.IsNull() {
			*name1 = r.Version.Name.ValueString()
		} else {
			name1 = nil
		}
		version = &shared.CreatePipelineVersionRequest{
			Name: name1,
		}
	}
	out := shared.CreatePipelineRequest{
		Description: description,
		Icon:        icon,
		LabelIds:    labelIds,
		Launch:      launch,
		Name:        name,
		Version:     version,
	}

	return &out, diags
}

func (r *PipelineResourceModel) ToSharedUpdatePipelineRequest(ctx context.Context) (*shared.UpdatePipelineRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	icon := new(string)
	if !r.Icon.IsUnknown() && !r.Icon.IsNull() {
		*icon = r.Icon.ValueString()
	} else {
		icon = nil
	}
	labelIds := make([]int64, 0, len(r.LabelIds))
	for labelIdsIndex := range r.LabelIds {
		labelIds = append(labelIds, r.LabelIds[labelIdsIndex].ValueInt64())
	}
	var launch *shared.WorkflowLaunchRequest
	computeEnvID := new(string)
	if !r.Launch.ComputeEnvID.IsUnknown() && !r.Launch.ComputeEnvID.IsNull() {
		*computeEnvID = r.Launch.ComputeEnvID.ValueString()
	} else {
		computeEnvID = nil
	}
	configProfiles := make([]string, 0, len(r.Launch.ConfigProfiles))
	for configProfilesIndex := range r.Launch.ConfigProfiles {
		configProfiles = append(configProfiles, r.Launch.ConfigProfiles[configProfilesIndex].ValueString())
	}
	configText := new(string)
	if !r.Launch.ConfigText.IsUnknown() && !r.Launch.ConfigText.IsNull() {
		*configText = r.Launch.ConfigText.ValueString()
	} else {
		configText = nil
	}
	entryName := new(string)
	if !r.Launch.EntryName.IsUnknown() && !r.Launch.EntryName.IsNull() {
		*entryName = r.Launch.EntryName.ValueString()
	} else {
		entryName = nil
	}
	headJobCpus := new(int)
	if !r.Launch.HeadJobCpus.IsUnknown() && !r.Launch.HeadJobCpus.IsNull() {
		*headJobCpus = int(r.Launch.HeadJobCpus.ValueInt32())
	} else {
		headJobCpus = nil
	}
	headJobMemoryMb := new(int)
	if !r.Launch.HeadJobMemoryMb.IsUnknown() && !r.Launch.HeadJobMemoryMb.IsNull() {
		*headJobMemoryMb = int(r.Launch.HeadJobMemoryMb.ValueInt32())
	} else {
		headJobMemoryMb = nil
	}
	labelIds1 := make([]int64, 0, len(r.Launch.LabelIds))
	for labelIdsIndex1 := range r.Launch.LabelIds {
		labelIds1 = append(labelIds1, r.Launch.LabelIds[labelIdsIndex1].ValueInt64())
	}
	mainScript := new(string)
	if !r.Launch.MainScript.IsUnknown() && !r.Launch.MainScript.IsNull() {
		*mainScript = r.Launch.MainScript.ValueString()
	} else {
		mainScript = nil
	}
	paramsText := new(string)
	if !r.Launch.ParamsText.IsUnknown() && !r.Launch.ParamsText.IsNull() {
		*paramsText = r.Launch.ParamsText.ValueString()
	} else {
		paramsText = nil
	}
	pipeline := new(string)
	if !r.Launch.Pipeline.IsUnknown() && !r.Launch.Pipeline.IsNull() {
		*pipeline = r.Launch.Pipeline.ValueString()
	} else {
		pipeline = nil
	}
	pipelineSchemaID := new(int64)
	if !r.Launch.PipelineSchemaID.IsUnknown() && !r.Launch.PipelineSchemaID.IsNull() {
		*pipelineSchemaID = r.Launch.PipelineSchemaID.ValueInt64()
	} else {
		pipelineSchemaID = nil
	}
	postRunScript := new(string)
	if !r.Launch.PostRunScript.IsUnknown() && !r.Launch.PostRunScript.IsNull() {
		*postRunScript = r.Launch.PostRunScript.ValueString()
	} else {
		postRunScript = nil
	}
	preRunScript := new(string)
	if !r.Launch.PreRunScript.IsUnknown() && !r.Launch.PreRunScript.IsNull() {
		*preRunScript = r.Launch.PreRunScript.ValueString()
	} else {
		preRunScript = nil
	}
	pullLatest := new(bool)
	if !r.Launch.PullLatest.IsUnknown() && !r.Launch.PullLatest.IsNull() {
		*pullLatest = r.Launch.PullLatest.ValueBool()
	} else {
		pullLatest = nil
	}
	resume := new(bool)
	if !r.Launch.Resume.IsUnknown() && !r.Launch.Resume.IsNull() {
		*resume = r.Launch.Resume.ValueBool()
	} else {
		resume = nil
	}
	revision := new(string)
	if !r.Launch.Revision.IsUnknown() && !r.Launch.Revision.IsNull() {
		*revision = r.Launch.Revision.ValueString()
	} else {
		revision = nil
	}
	runName := new(string)
	if !r.Launch.RunName.IsUnknown() && !r.Launch.RunName.IsNull() {
		*runName = r.Launch.RunName.ValueString()
	} else {
		runName = nil
	}
	schemaName := new(string)
	if !r.Launch.SchemaName.IsUnknown() && !r.Launch.SchemaName.IsNull() {
		*schemaName = r.Launch.SchemaName.ValueString()
	} else {
		schemaName = nil
	}
	stubRun := new(bool)
	if !r.Launch.StubRun.IsUnknown() && !r.Launch.StubRun.IsNull() {
		*stubRun = r.Launch.StubRun.ValueBool()
	} else {
		stubRun = nil
	}
	towerConfig := new(string)
	if !r.Launch.TowerConfig.IsUnknown() && !r.Launch.TowerConfig.IsNull() {
		*towerConfig = r.Launch.TowerConfig.ValueString()
	} else {
		towerConfig = nil
	}
	userSecrets := make([]string, 0, len(r.Launch.UserSecrets))
	for userSecretsIndex := range r.Launch.UserSecrets {
		userSecrets = append(userSecrets, r.Launch.UserSecrets[userSecretsIndex].ValueString())
	}
	workDir := new(string)
	if !r.Launch.WorkDir.IsUnknown() && !r.Launch.WorkDir.IsNull() {
		*workDir = r.Launch.WorkDir.ValueString()
	} else {
		workDir = nil
	}
	workspaceSecrets := make([]string, 0, len(r.Launch.WorkspaceSecrets))
	for workspaceSecretsIndex := range r.Launch.WorkspaceSecrets {
		workspaceSecrets = append(workspaceSecrets, r.Launch.WorkspaceSecrets[workspaceSecretsIndex].ValueString())
	}
	launch = &shared.WorkflowLaunchRequest{
		ComputeEnvID:     computeEnvID,
		ConfigProfiles:   configProfiles,
		ConfigText:       configText,
		EntryName:        entryName,
		HeadJobCpus:      headJobCpus,
		HeadJobMemoryMb:  headJobMemoryMb,
		LabelIds:         labelIds1,
		MainScript:       mainScript,
		ParamsText:       paramsText,
		Pipeline:         pipeline,
		PipelineSchemaID: pipelineSchemaID,
		PostRunScript:    postRunScript,
		PreRunScript:     preRunScript,
		PullLatest:       pullLatest,
		Resume:           resume,
		Revision:         revision,
		RunName:          runName,
		SchemaName:       schemaName,
		StubRun:          stubRun,
		TowerConfig:      towerConfig,
		UserSecrets:      userSecrets,
		WorkDir:          workDir,
		WorkspaceSecrets: workspaceSecrets,
	}
	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	out := shared.UpdatePipelineRequest{
		Description: description,
		Icon:        icon,
		LabelIds:    labelIds,
		Launch:      launch,
		Name:        name,
	}

	return &out, diags
}
