// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/seqeralabs/terraform-provider-seqera/internal/provider/typeconvert"
	tfTypes "github.com/seqeralabs/terraform-provider-seqera/internal/provider/types"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/operations"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
)

func (r *WorkflowsResourceModel) RefreshFromSharedDescribeWorkflowResponse(ctx context.Context, resp *shared.DescribeWorkflowResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.PipelineInfo == nil {
			r.PipelineInfo = nil
		} else {
			r.PipelineInfo = &tfTypes.PipelineMinInfoResponse{}
			r.PipelineInfo.ID = types.Int64PointerValue(resp.PipelineInfo.ID)
			if resp.PipelineInfo.Version == nil {
				r.PipelineInfo.Version = nil
			} else {
				r.PipelineInfo.Version = &tfTypes.PipelineMinInfoResponsePipelineVersionMinInfoResponse{}
				r.PipelineInfo.Version.DateCreated = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.PipelineInfo.Version.DateCreated))
				r.PipelineInfo.Version.Hash = types.StringPointerValue(resp.PipelineInfo.Version.Hash)
				r.PipelineInfo.Version.ID = types.StringPointerValue(resp.PipelineInfo.Version.ID)
				r.PipelineInfo.Version.IsDefault = types.BoolPointerValue(resp.PipelineInfo.Version.IsDefault)
				r.PipelineInfo.Version.IsDraftVersion = types.BoolPointerValue(resp.PipelineInfo.Version.IsDraftVersion)
				r.PipelineInfo.Version.LastUpdated = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.PipelineInfo.Version.LastUpdated))
				r.PipelineInfo.Version.Name = types.StringPointerValue(resp.PipelineInfo.Version.Name)
			}
			r.PipelineInfo.WorkspaceID = types.Int64PointerValue(resp.PipelineInfo.WorkspaceID)
		}
		if resp.Workflow == nil {
			r.Workflow = nil
		} else {
			r.Workflow = &tfTypes.WorkflowMaxDbDto{}
			r.Workflow.CommandLine = types.StringPointerValue(resp.Workflow.CommandLine)
			r.Workflow.Complete = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.Workflow.Complete))
			if resp.Workflow.ConfigFiles != nil {
				r.Workflow.ConfigFiles = make([]types.String, 0, len(resp.Workflow.ConfigFiles))
				for _, v := range resp.Workflow.ConfigFiles {
					r.Workflow.ConfigFiles = append(r.Workflow.ConfigFiles, types.StringValue(v))
				}
			} else {
				r.Workflow.ConfigFiles = nil
			}
			r.Workflow.ConfigText = types.StringPointerValue(resp.Workflow.ConfigText)
			r.Workflow.DateCreated = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.Workflow.DateCreated))
			r.Workflow.Deleted = types.BoolPointerValue(resp.Workflow.Deleted)
			if resp.Workflow.Fusion == nil {
				r.Workflow.Fusion = nil
			} else {
				r.Workflow.Fusion = &tfTypes.WfFusionMeta{}
				r.Workflow.Fusion.Enabled = types.BoolPointerValue(resp.Workflow.Fusion.Enabled)
				r.Workflow.Fusion.Version = types.StringPointerValue(resp.Workflow.Fusion.Version)
			}
			r.Workflow.ID = types.StringPointerValue(resp.Workflow.ID)
			r.Workflow.LastUpdated = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.Workflow.LastUpdated))
			r.Workflow.LaunchID = types.StringPointerValue(resp.Workflow.LaunchID)
			r.Workflow.LogFile = types.StringPointerValue(resp.Workflow.LogFile)
			r.Workflow.OperationID = types.StringPointerValue(resp.Workflow.OperationID)
			r.Workflow.OutFile = types.StringPointerValue(resp.Workflow.OutFile)
			r.Workflow.OwnerID = types.Int64PointerValue(resp.Workflow.OwnerID)
			if resp.Workflow.Params != nil {
				r.Workflow.Params = make(map[string]jsontypes.Normalized, len(resp.Workflow.Params))
				for key, value := range resp.Workflow.Params {
					result, _ := json.Marshal(value)
					r.Workflow.Params[key] = jsontypes.NewNormalizedValue(string(result))
				}
			}
			r.Workflow.Profile = types.StringPointerValue(resp.Workflow.Profile)
			r.Workflow.ProjectName = types.StringPointerValue(resp.Workflow.ProjectName)
			r.Workflow.Repository = types.StringPointerValue(resp.Workflow.Repository)
			r.Workflow.RequiresAttention = types.BoolPointerValue(resp.Workflow.RequiresAttention)
			r.Workflow.Resume = types.BoolPointerValue(resp.Workflow.Resume)
			r.Workflow.Revision = types.StringPointerValue(resp.Workflow.Revision)
			r.Workflow.RunName = types.StringPointerValue(resp.Workflow.RunName)
			r.Workflow.ScriptName = types.StringPointerValue(resp.Workflow.ScriptName)
			r.Workflow.SessionID = types.StringPointerValue(resp.Workflow.SessionID)
			r.Workflow.Start = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.Workflow.Start))
			if resp.Workflow.Status != nil {
				r.Workflow.Status = types.StringValue(string(*resp.Workflow.Status))
			} else {
				r.Workflow.Status = types.StringNull()
			}
			r.Workflow.Submit = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.Workflow.Submit))
			if resp.Workflow.Wave == nil {
				r.Workflow.Wave = nil
			} else {
				r.Workflow.Wave = &tfTypes.WfWaveMeta{}
				r.Workflow.Wave.Enabled = types.BoolPointerValue(resp.Workflow.Wave.Enabled)
			}
			r.Workflow.WorkDir = types.StringPointerValue(resp.Workflow.WorkDir)
		}
		r.WorkspaceID = types.Int64PointerValue(resp.WorkspaceID)
	}

	return diags
}

func (r *WorkflowsResourceModel) RefreshFromSharedSubmitWorkflowLaunchResponse(ctx context.Context, resp *shared.SubmitWorkflowLaunchResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.WorkflowID = types.StringPointerValue(resp.WorkflowID)
	}

	return diags
}

func (r *WorkflowsResourceModel) ToOperationsCreateWorkflowLaunchRequest(ctx context.Context) (*operations.CreateWorkflowLaunchRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var workspaceID int64
	workspaceID = r.WorkspaceID.ValueInt64()

	sourceWorkspaceID := new(int64)
	if !r.SourceWorkspaceID.IsUnknown() && !r.SourceWorkspaceID.IsNull() {
		*sourceWorkspaceID = r.SourceWorkspaceID.ValueInt64()
	} else {
		sourceWorkspaceID = nil
	}
	submitWorkflowLaunchRequest, submitWorkflowLaunchRequestDiags := r.ToSharedSubmitWorkflowLaunchRequest(ctx)
	diags.Append(submitWorkflowLaunchRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreateWorkflowLaunchRequest{
		WorkspaceID:                 workspaceID,
		SourceWorkspaceID:           sourceWorkspaceID,
		SubmitWorkflowLaunchRequest: *submitWorkflowLaunchRequest,
	}

	return &out, diags
}

func (r *WorkflowsResourceModel) ToOperationsDeleteWorkflowRequest(ctx context.Context) (*operations.DeleteWorkflowRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var workflowID string
	workflowID = r.WorkflowID.ValueString()

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	force := new(bool)
	if !r.Force.IsUnknown() && !r.Force.IsNull() {
		*force = r.Force.ValueBool()
	} else {
		force = nil
	}
	out := operations.DeleteWorkflowRequest{
		WorkflowID:  workflowID,
		WorkspaceID: workspaceID,
		Force:       force,
	}

	return &out, diags
}

func (r *WorkflowsResourceModel) ToOperationsDescribeWorkflowRequest(ctx context.Context) (*operations.DescribeWorkflowRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var workflowID string
	workflowID = r.WorkflowID.ValueString()

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	out := operations.DescribeWorkflowRequest{
		WorkflowID:  workflowID,
		WorkspaceID: workspaceID,
	}

	return &out, diags
}

func (r *WorkflowsResourceModel) ToSharedSubmitWorkflowLaunchRequest(ctx context.Context) (*shared.SubmitWorkflowLaunchRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	launch, launchDiags := r.ToSharedWorkflowLaunchRequest(ctx)
	diags.Append(launchDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := shared.SubmitWorkflowLaunchRequest{
		Launch: *launch,
	}

	return &out, diags
}

func (r *WorkflowsResourceModel) ToSharedWorkflowLaunchRequest(ctx context.Context) (*shared.WorkflowLaunchRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	computeEnvID := new(string)
	if !r.ComputeEnvID.IsUnknown() && !r.ComputeEnvID.IsNull() {
		*computeEnvID = r.ComputeEnvID.ValueString()
	} else {
		computeEnvID = nil
	}
	configProfiles := make([]string, 0, len(r.ConfigProfiles))
	for configProfilesIndex := range r.ConfigProfiles {
		configProfiles = append(configProfiles, r.ConfigProfiles[configProfilesIndex].ValueString())
	}
	configText := new(string)
	if !r.ConfigText.IsUnknown() && !r.ConfigText.IsNull() {
		*configText = r.ConfigText.ValueString()
	} else {
		configText = nil
	}
	entryName := new(string)
	if !r.EntryName.IsUnknown() && !r.EntryName.IsNull() {
		*entryName = r.EntryName.ValueString()
	} else {
		entryName = nil
	}
	headJobCpus := new(int)
	if !r.HeadJobCpus.IsUnknown() && !r.HeadJobCpus.IsNull() {
		*headJobCpus = int(r.HeadJobCpus.ValueInt32())
	} else {
		headJobCpus = nil
	}
	headJobMemoryMb := new(int)
	if !r.HeadJobMemoryMb.IsUnknown() && !r.HeadJobMemoryMb.IsNull() {
		*headJobMemoryMb = int(r.HeadJobMemoryMb.ValueInt32())
	} else {
		headJobMemoryMb = nil
	}
	labelIds := make([]int64, 0, len(r.LabelIds))
	for labelIdsIndex := range r.LabelIds {
		labelIds = append(labelIds, r.LabelIds[labelIdsIndex].ValueInt64())
	}
	mainScript := new(string)
	if !r.MainScript.IsUnknown() && !r.MainScript.IsNull() {
		*mainScript = r.MainScript.ValueString()
	} else {
		mainScript = nil
	}
	paramsText := new(string)
	if !r.ParamsText.IsUnknown() && !r.ParamsText.IsNull() {
		*paramsText = r.ParamsText.ValueString()
	} else {
		paramsText = nil
	}
	pipeline := new(string)
	if !r.Pipeline.IsUnknown() && !r.Pipeline.IsNull() {
		*pipeline = r.Pipeline.ValueString()
	} else {
		pipeline = nil
	}
	pipelineSchemaID := new(int64)
	if !r.PipelineSchemaID.IsUnknown() && !r.PipelineSchemaID.IsNull() {
		*pipelineSchemaID = r.PipelineSchemaID.ValueInt64()
	} else {
		pipelineSchemaID = nil
	}
	postRunScript := new(string)
	if !r.PostRunScript.IsUnknown() && !r.PostRunScript.IsNull() {
		*postRunScript = r.PostRunScript.ValueString()
	} else {
		postRunScript = nil
	}
	preRunScript := new(string)
	if !r.PreRunScript.IsUnknown() && !r.PreRunScript.IsNull() {
		*preRunScript = r.PreRunScript.ValueString()
	} else {
		preRunScript = nil
	}
	pullLatest := new(bool)
	if !r.PullLatest.IsUnknown() && !r.PullLatest.IsNull() {
		*pullLatest = r.PullLatest.ValueBool()
	} else {
		pullLatest = nil
	}
	resume := new(bool)
	if !r.Resume.IsUnknown() && !r.Resume.IsNull() {
		*resume = r.Resume.ValueBool()
	} else {
		resume = nil
	}
	revision := new(string)
	if !r.Revision.IsUnknown() && !r.Revision.IsNull() {
		*revision = r.Revision.ValueString()
	} else {
		revision = nil
	}
	runName := new(string)
	if !r.RunName.IsUnknown() && !r.RunName.IsNull() {
		*runName = r.RunName.ValueString()
	} else {
		runName = nil
	}
	schemaName := new(string)
	if !r.SchemaName.IsUnknown() && !r.SchemaName.IsNull() {
		*schemaName = r.SchemaName.ValueString()
	} else {
		schemaName = nil
	}
	stubRun := new(bool)
	if !r.StubRun.IsUnknown() && !r.StubRun.IsNull() {
		*stubRun = r.StubRun.ValueBool()
	} else {
		stubRun = nil
	}
	towerConfig := new(string)
	if !r.TowerConfig.IsUnknown() && !r.TowerConfig.IsNull() {
		*towerConfig = r.TowerConfig.ValueString()
	} else {
		towerConfig = nil
	}
	userSecrets := make([]string, 0, len(r.UserSecrets))
	for userSecretsIndex := range r.UserSecrets {
		userSecrets = append(userSecrets, r.UserSecrets[userSecretsIndex].ValueString())
	}
	workDir := new(string)
	if !r.WorkDir.IsUnknown() && !r.WorkDir.IsNull() {
		*workDir = r.WorkDir.ValueString()
	} else {
		workDir = nil
	}
	workspaceSecrets := make([]string, 0, len(r.WorkspaceSecrets))
	for workspaceSecretsIndex := range r.WorkspaceSecrets {
		workspaceSecrets = append(workspaceSecrets, r.WorkspaceSecrets[workspaceSecretsIndex].ValueString())
	}
	out := shared.WorkflowLaunchRequest{
		ComputeEnvID:     computeEnvID,
		ConfigProfiles:   configProfiles,
		ConfigText:       configText,
		EntryName:        entryName,
		HeadJobCpus:      headJobCpus,
		HeadJobMemoryMb:  headJobMemoryMb,
		LabelIds:         labelIds,
		MainScript:       mainScript,
		ParamsText:       paramsText,
		Pipeline:         pipeline,
		PipelineSchemaID: pipelineSchemaID,
		PostRunScript:    postRunScript,
		PreRunScript:     preRunScript,
		PullLatest:       pullLatest,
		Resume:           resume,
		Revision:         revision,
		RunName:          runName,
		SchemaName:       schemaName,
		StubRun:          stubRun,
		TowerConfig:      towerConfig,
		UserSecrets:      userSecrets,
		WorkDir:          workDir,
		WorkspaceSecrets: workspaceSecrets,
	}

	return &out, diags
}
