// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GoogleBatchServiceConfiguration struct {
	BootDiskImage               types.String            `tfsdk:"boot_disk_image"`
	BootDiskSizeGb              types.Int32             `tfsdk:"boot_disk_size_gb"`
	ComputeJobsInstanceTemplate types.String            `tfsdk:"compute_jobs_instance_template"`
	ComputeJobsMachineType      []types.String          `tfsdk:"compute_jobs_machine_type"`
	CopyImage                   types.String            `tfsdk:"copy_image"`
	CPUPlatform                 types.String            `tfsdk:"cpu_platform"`
	DebugMode                   types.Int32             `tfsdk:"debug_mode"`
	EnableFusion                types.Bool              `tfsdk:"enable_fusion"`
	EnableWave                  types.Bool              `tfsdk:"enable_wave"`
	Environment                 []ConfigEnvVariable     `tfsdk:"environment"`
	FusionSnapshots             types.Bool              `tfsdk:"fusion_snapshots"`
	HeadJobCpus                 types.Int32             `tfsdk:"head_job_cpus"`
	HeadJobInstanceTemplate     types.String            `tfsdk:"head_job_instance_template"`
	HeadJobMemoryMb             types.Int32             `tfsdk:"head_job_memory_mb"`
	Labels                      map[string]types.String `tfsdk:"labels"`
	Location                    types.String            `tfsdk:"location"`
	MachineType                 types.String            `tfsdk:"machine_type"`
	Network                     types.String            `tfsdk:"network"`
	NetworkTags                 []types.String          `tfsdk:"network_tags"`
	NextflowConfig              types.String            `tfsdk:"nextflow_config"`
	NfsMount                    types.String            `tfsdk:"nfs_mount"`
	NfsTarget                   types.String            `tfsdk:"nfs_target"`
	PostRunScript               types.String            `tfsdk:"post_run_script"`
	PreRunScript                types.String            `tfsdk:"pre_run_script"`
	ProjectID                   types.String            `tfsdk:"project_id"`
	ServiceAccount              types.String            `tfsdk:"service_account"`
	Spot                        types.Bool              `tfsdk:"spot"`
	SSHDaemon                   types.Bool              `tfsdk:"ssh_daemon"`
	SSHImage                    types.String            `tfsdk:"ssh_image"`
	Subnetwork                  types.String            `tfsdk:"subnetwork"`
	UsePrivateAddress           types.Bool              `tfsdk:"use_private_address"`
	WorkDir                     types.String            `tfsdk:"work_dir"`
}
