// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type LocalExecutionConfiguration struct {
	Environment    []ConfigEnvVariable `tfsdk:"environment"`
	Fusion2Enabled types.Bool          `tfsdk:"fusion2_enabled"`
	NextflowConfig types.String        `tfsdk:"nextflow_config"`
	PostRunScript  types.String        `tfsdk:"post_run_script"`
	PreRunScript   types.String        `tfsdk:"pre_run_script"`
	SchedConfig    *SchedConfig        `tfsdk:"sched_config"`
	SchedEnabled   types.Bool          `tfsdk:"sched_enabled"`
	WaveEnabled    types.Bool          `tfsdk:"wave_enabled"`
	WorkDir        types.String        `tfsdk:"work_dir"`
}
