// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type MountData struct {
	DataLinkID types.String `tfsdk:"data_link_id"`
	Path       types.String `tfsdk:"path"`
}
