// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type PipelineMinInfoResponsePipelineVersionMinInfoResponse struct {
	ID             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	DateCreated    types.String `tfsdk:"date_created"`
	LastUpdated    types.String `tfsdk:"last_updated"`
	Hash           types.String `tfsdk:"hash"`
	IsDefault      types.Bool   `tfsdk:"is_default"`
	IsDraftVersion types.Bool   `tfsdk:"is_draft_version"`
}
