// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type SecurityKeys struct {
	Codecommit    *AWSCodeCommitCredentials     `queryParam:"inline" tfsdk:"codecommit"`
	Aws           *AWSCredentials               `queryParam:"inline" tfsdk:"aws"`
	AzureCloud    *AzureCloudCredentials        `queryParam:"inline" tfsdk:"azure_cloud"`
	AzureEntra    *AzureEntraCredentials        `queryParam:"inline" tfsdk:"azure_entra"`
	Azurerepos    *AzureReposCredentials        `queryParam:"inline" tfsdk:"azurerepos"`
	Azure         *AzureCredentials             `queryParam:"inline" tfsdk:"azure"`
	Bitbucket     *BitBucketCredentials         `queryParam:"inline" tfsdk:"bitbucket"`
	ContainerReg  *ContainerRegistryCredentials `queryParam:"inline" tfsdk:"container_reg"`
	Github        *GitHubCredentials            `queryParam:"inline" tfsdk:"github"`
	Gitlab        *GitLabCredentials            `queryParam:"inline" tfsdk:"gitlab"`
	Gitea         *GiteaCredentials             `queryParam:"inline" tfsdk:"gitea"`
	Google        *GoogleCredentials            `queryParam:"inline" tfsdk:"google"`
	K8s           *KubernetesCredentials        `queryParam:"inline" tfsdk:"k8s"`
	Local         *LocalSecurityKeys            `queryParam:"inline" tfsdk:"local"`
	S3            *S3CompatibleCredentials      `queryParam:"inline" tfsdk:"s3"`
	SSH           *SSHCredentials               `queryParam:"inline" tfsdk:"ssh"`
	Seqeracompute *SeqeraComputeCredentials     `queryParam:"inline" tfsdk:"seqeracompute"`
	TwAgent       *TowerAgentCredentials        `queryParam:"inline" tfsdk:"tw_agent"`
}
